name: 'Build Arch Packages'
description: 'Build Arch Linux packages with shared runtime'
inputs:
  version:
    description: 'Package version'
    required: true
  dotnet-version:
    description: '.NET version to use'
    required: false
    default: '10.0.x'

runs:
  using: 'composite'
  steps:
    - name: Build shared runtime payload
      uses: ./.github/actions/build-linux-installer-payload
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install Arch build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libarchive-tools zstd fakeroot

    - name: Build Arch packages
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        PAYLOAD_PATH="./installer-payload"
        INSTALL_DIR="/opt/nomercy"

        # Create package directory structure
        pkg_dir="arch-nomercy"
        mkdir -p "${pkg_dir}/pkg${INSTALL_DIR}"
        mkdir -p "${pkg_dir}/pkg/usr/bin"
        mkdir -p "${pkg_dir}/pkg/usr/share/applications"
        mkdir -p "${pkg_dir}/pkg/usr/share/icons/hicolor/scalable/apps"
        mkdir -p "${pkg_dir}/pkg/usr/share/licenses/nomercy"

        # Copy shared runtime payload
        cp -R "${PAYLOAD_PATH}/"* "${pkg_dir}/pkg${INSTALL_DIR}/"
        chmod 755 "${pkg_dir}/pkg${INSTALL_DIR}/NoMercyMediaServer"
        chmod 755 "${pkg_dir}/pkg${INSTALL_DIR}/NoMercyApp"
        chmod 755 "${pkg_dir}/pkg${INSTALL_DIR}/NoMercyMediaServerService"
        chmod 755 "${pkg_dir}/pkg${INSTALL_DIR}/nomercy"

        # Symlinks in /usr/bin
        ln -s "${INSTALL_DIR}/NoMercyMediaServer" "${pkg_dir}/pkg/usr/bin/nomercymediaserver"
        ln -s "${INSTALL_DIR}/NoMercyApp" "${pkg_dir}/pkg/usr/bin/nomercyapp"
        ln -s "${INSTALL_DIR}/NoMercyMediaServerService" "${pkg_dir}/pkg/usr/bin/nomercymediaserverservice"
        ln -s "${INSTALL_DIR}/nomercy" "${pkg_dir}/pkg/usr/bin/nomercy"

        # Desktop files
        for df in NoMercy-MediaServer.desktop NoMercy-MediaServer-Service.desktop NoMercy-App.desktop; do
          if [ -f "./assets/linux/${df}" ]; then
            cp "./assets/linux/${df}" "${pkg_dir}/pkg/usr/share/applications/"
          fi
        done

        # Icon
        cp "./assets/icons/icon.png" "${pkg_dir}/pkg/usr/share/icons/hicolor/scalable/apps/NoMercy-MediaServer.png"

        # License
        echo "Proprietary software. All rights reserved." > "${pkg_dir}/pkg/usr/share/licenses/nomercy/LICENSE"

        # Create PKGBUILD (for reference)
        cat > "${pkg_dir}/PKGBUILD" << EOF
        # Maintainer: NoMercy Entertainment <support@nomercy.tv>
        pkgname=nomercy
        pkgver=${VERSION}
        pkgrel=1
        pkgdesc="NoMercy MediaServer - complete installation"
        arch=('x86_64')
        url="https://nomercy.tv"
        license=('custom')
        depends=('glibc')
        EOF

        # Create .PKGINFO
        cat > "${pkg_dir}/pkg/.PKGINFO" << EOF
        pkgname = nomercy
        pkgbase = nomercy
        pkgver = ${VERSION}-1
        pkgdesc = NoMercy MediaServer - complete installation
        url = https://nomercy.tv
        builddate = $(date +%s)
        packager = NoMercy Entertainment <support@nomercy.tv>
        size = $(du -sb "${pkg_dir}/pkg" | cut -f1)
        arch = x86_64
        license = custom
        depend = glibc
        EOF

        # Create .MTREE
        cd "${pkg_dir}/pkg"
        find . -type f -exec stat -c '%n %Y %s' {} \; | sort > .MTREE
        cd ../..

        # Create package
        mkdir -p packages/arch/pool/x86_64
        cd "${pkg_dir}/pkg"
        tar --use-compress-program=zstd -cf "../../packages/arch/pool/x86_64/nomercy-${VERSION}-1-x86_64.pkg.tar.zst" .
        cd ../..
        rm -rf "${pkg_dir}"
        echo "Successfully created nomercy Arch package"

        # Create simple database
        cd packages/arch/pool/x86_64
        if ls *.pkg.tar.zst >/dev/null 2>&1; then
          echo "# NoMercy Arch Repository Database" > nomercy.db
          echo "# Generated on $(date)" >> nomercy.db
          echo "" >> nomercy.db

          for pkg in *.pkg.tar.zst; do
            echo "[Package]" >> nomercy.db
            echo "Name: ${pkg%%-*}" >> nomercy.db
            echo "Version: $(echo "$pkg" | cut -d'-' -f2-3)" >> nomercy.db
            echo "Filename: $pkg" >> nomercy.db
            echo "Size: $(stat -c%s "$pkg")" >> nomercy.db
            echo "" >> nomercy.db
          done

          gzip -c nomercy.db > nomercy.db.tar.gz

          echo "Created Arch packages:"
          ls -la *.pkg.tar.zst
        else
          echo "ERROR: No package files found"
          exit 1
        fi

    - name: Upload Arch artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arch-packages
        path: packages/arch/
