// -----------------------------------------------------------------------------
//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.
//
//  This file is part of NoMercy MediaServer, source-available software (NOT open
//  source). Personal use and contributions are welcome; distribution, resale,
//  relicensing, and commercial exploitation are prohibited without explicit
//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.
//
//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary
// -----------------------------------------------------------------------------

// Generated by tools/nm-components. Do not edit.


namespace NoMercy.Api.DTOs.Media.Nm;

/// <summary>
/// Builds a component payload from its typed props.
/// </summary>
public static class NmBuilder
{
    private static NmComponent Build(string component, object props, string? id) =>
        new()
        {
            Id = id,
            Component = component,
            Props = props,
        };

    /// <summary>
    /// A NMAvatar carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Avatar(NMAvatarProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Avatar, props, props.Id);
    }

    /// <summary>
    /// A NMBadge carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Badge(NMBadgeProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Badge, props, props.Id);
    }

    /// <summary>
    /// A NMDivider carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Divider(NMDividerProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Divider, props, props.Id);
    }

    /// <summary>
    /// A NMFormLabel carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent FormLabel(NMFormLabelProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.FormLabel, props, props.Id);
    }

    /// <summary>
    /// A NMHelper carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Helper(NMHelperProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Helper, props, props.Id);
    }

    /// <summary>
    /// A NMImage carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Image(NMImageProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Image, props, props.Id);
    }

    /// <summary>
    /// A NMLink carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Link(NMLinkProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Link, props, props.Id);
    }

    /// <summary>
    /// A NMProgress carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Progress(NMProgressProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Progress, props, props.Id);
    }

    /// <summary>
    /// A NMSkeleton carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Skeleton(NMSkeletonProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Skeleton, props, props.Id);
    }

    /// <summary>
    /// A NMSpinner carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Spinner(NMSpinnerProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Spinner, props, props.Id);
    }

    /// <summary>
    /// A NMTag carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Tag(NMTagProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Tag, props, props.Id);
    }

    /// <summary>
    /// A NMButton carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Button(NMButtonProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Button, props, props.Id);
    }

    /// <summary>
    /// A NMCheckbox carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Checkbox(NMCheckboxProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Checkbox, props, props.Id);
    }

    /// <summary>
    /// A NMInput carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Input(NMInputProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Input, props, props.Id);
    }

    /// <summary>
    /// A NMRadio carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Radio(NMRadioProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Radio, props, props.Id);
    }

    /// <summary>
    /// A NMRating carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Rating(NMRatingProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Rating, props, props.Id);
    }

    /// <summary>
    /// A NMSlider carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Slider(NMSliderProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Slider, props, props.Id);
    }

    /// <summary>
    /// A NMTextarea carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Textarea(NMTextareaProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Textarea, props, props.Id);
    }

    /// <summary>
    /// A NMToggle carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Toggle(NMToggleProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Toggle, props, props.Id);
    }

    /// <summary>
    /// A NMBadgeGroup carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent BadgeGroup(NMBadgeGroupProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.BadgeGroup, props, props.Id);
    }

    /// <summary>
    /// A NMBreadcrumb carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Breadcrumb(NMBreadcrumbProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Breadcrumb, props, props.Id);
    }

    /// <summary>
    /// A NMButtonGroup carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent ButtonGroup(NMButtonGroupProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.ButtonGroup, props, props.Id);
    }

    /// <summary>
    /// A NMCheckboxGroup carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent CheckboxGroup(NMCheckboxGroupProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.CheckboxGroup, props, props.Id);
    }

    /// <summary>
    /// A NMPagination carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Pagination(NMPaginationProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Pagination, props, props.Id);
    }

    /// <summary>
    /// A NMRadioGroup carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent RadioGroup(NMRadioGroupProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.RadioGroup, props, props.Id);
    }

    /// <summary>
    /// A NMSegmented carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Segmented(NMSegmentedProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Segmented, props, props.Id);
    }

    /// <summary>
    /// A NMStepIndicator carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent StepIndicator(NMStepIndicatorProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.StepIndicator, props, props.Id);
    }

    /// <summary>
    /// A NMToggles carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Toggles(NMTogglesProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Toggles, props, props.Id);
    }

    /// <summary>
    /// A NMAlert carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Alert(NMAlertProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Alert, props, props.Id);
    }

    /// <summary>
    /// A NMCard carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Card(NMCardProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Card, props, props.Id);
    }

    /// <summary>
    /// A NMChat carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Chat(NMChatProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Chat, props, props.Id);
    }

    /// <summary>
    /// A NMContentFooter carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent ContentFooter(NMContentFooterProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.ContentFooter, props, props.Id);
    }

    /// <summary>
    /// A NMContentHeader carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent ContentHeader(NMContentHeaderProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.ContentHeader, props, props.Id);
    }

    /// <summary>
    /// A NMEmptyState carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent EmptyState(NMEmptyStateProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.EmptyState, props, props.Id);
    }

    /// <summary>
    /// A NMList carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent List(NMListProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.List, props, props.Id);
    }

    /// <summary>
    /// A NMMetrics carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Metrics(NMMetricsProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Metrics, props, props.Id);
    }

    /// <summary>
    /// A NMTable carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Table(NMTableProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Table, props, props.Id);
    }

    /// <summary>
    /// A NMColorPicker carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent ColorPicker(NMColorPickerProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.ColorPicker, props, props.Id);
    }

    /// <summary>
    /// A NMCombobox carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Combobox(NMComboboxProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Combobox, props, props.Id);
    }

    /// <summary>
    /// A NMCommandPalette carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent CommandPalette(NMCommandPaletteProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.CommandPalette, props, props.Id);
    }

    /// <summary>
    /// A NMDatePicker carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent DatePicker(NMDatePickerProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.DatePicker, props, props.Id);
    }

    /// <summary>
    /// A NMDrawer carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Drawer(NMDrawerProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Drawer, props, props.Id);
    }

    /// <summary>
    /// A NMDropdown carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Dropdown(NMDropdownProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Dropdown, props, props.Id);
    }

    /// <summary>
    /// A NMModal carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Modal(NMModalProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Modal, props, props.Id);
    }

    /// <summary>
    /// A NMPopover carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Popover(NMPopoverProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Popover, props, props.Id);
    }

    /// <summary>
    /// A NMSearchInput carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent SearchInput(NMSearchInputProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.SearchInput, props, props.Id);
    }

    /// <summary>
    /// A NMSelect carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Select(NMSelectProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Select, props, props.Id);
    }

    /// <summary>
    /// A NMToast carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Toast(NMToastProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Toast, props, props.Id);
    }

    /// <summary>
    /// A NMTooltip carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Tooltip(NMTooltipProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Tooltip, props, props.Id);
    }

    /// <summary>
    /// A NMAccordion carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Accordion(NMAccordionProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Accordion, props, props.Id);
    }

    /// <summary>
    /// A NMCarousel carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Carousel(NMCarouselProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Carousel, props, props.Id);
    }

    /// <summary>
    /// A NMFileUpload carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent FileUpload(NMFileUploadProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.FileUpload, props, props.Id);
    }

    /// <summary>
    /// A NMNavigation carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Navigation(NMNavigationProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Navigation, props, props.Id);
    }

    /// <summary>
    /// A NMStepper carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Stepper(NMStepperProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Stepper, props, props.Id);
    }

    /// <summary>
    /// A NMTabs carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent Tabs(NMTabsProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.Tabs, props, props.Id);
    }

    /// <summary>
    /// A NMTreeView carrying [props], with [children] appended to its items.
    /// </summary>
    public static NmComponent TreeView(NMTreeViewProps props, params NmComponent[] children)
    {
        if (children.Length > 0)
            props.Items = [.. props.Items, .. children];

        return Build(NmComponents.TreeView, props, props.Id);
    }

}
