name: 'Build DEB Packages'
description: 'Build Debian/Ubuntu packages with shared runtime'
inputs:
  version:
    description: 'Package version'
    required: true
  dotnet-version:
    description: '.NET version to use'
    required: false
    default: '10.0.x'

runs:
  using: 'composite'
  steps:
    - name: Build shared runtime payload
      uses: ./.github/actions/build-linux-installer-payload
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install DEB build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev devscripts fakeroot build-essential

    - name: Build DEB packages
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        PAYLOAD_PATH="./installer-payload"
        INSTALL_DIR="/opt/nomercy"

        # --- Main package: nomercy (shared runtime + all executables) ---
        PACKAGE_ROOT="./packages/debian-nomercy"
        rm -rf "${PACKAGE_ROOT}"

        mkdir -p "${PACKAGE_ROOT}/DEBIAN"
        mkdir -p "${PACKAGE_ROOT}${INSTALL_DIR}"
        mkdir -p "${PACKAGE_ROOT}/usr/bin"
        mkdir -p "${PACKAGE_ROOT}/usr/share/applications"
        mkdir -p "${PACKAGE_ROOT}/usr/share/icons/hicolor/scalable/apps"
        mkdir -p "${PACKAGE_ROOT}/usr/lib/systemd/user"
        mkdir -p "${PACKAGE_ROOT}/usr/share/doc/nomercy"

        # Copy entire shared runtime payload
        cp -R "${PAYLOAD_PATH}/"* "${PACKAGE_ROOT}${INSTALL_DIR}/"
        chmod 755 "${PACKAGE_ROOT}${INSTALL_DIR}/NoMercyMediaServer"
        chmod 755 "${PACKAGE_ROOT}${INSTALL_DIR}/NoMercyApp"
        chmod 755 "${PACKAGE_ROOT}${INSTALL_DIR}/NoMercyMediaServerService"
        chmod 755 "${PACKAGE_ROOT}${INSTALL_DIR}/nomercy"

        # Create symlinks in /usr/bin
        ln -s "${INSTALL_DIR}/NoMercyMediaServer" "${PACKAGE_ROOT}/usr/bin/nomercymediaserver"
        ln -s "${INSTALL_DIR}/NoMercyApp" "${PACKAGE_ROOT}/usr/bin/nomercyapp"
        ln -s "${INSTALL_DIR}/NoMercyMediaServerService" "${PACKAGE_ROOT}/usr/bin/nomercymediaserverservice"
        ln -s "${INSTALL_DIR}/nomercy" "${PACKAGE_ROOT}/usr/bin/nomercy"

        # Copy desktop files
        for df in NoMercy-MediaServer.desktop NoMercy-MediaServer-Service.desktop NoMercy-App.desktop; do
          if [ -f "./assets/linux/${df}" ]; then
            install -Dm644 "./assets/linux/${df}" "${PACKAGE_ROOT}/usr/share/applications/"
          fi
        done

        # Copy icon
        install -Dm644 "./assets/icons/icon.png" \
          "${PACKAGE_ROOT}/usr/share/icons/hicolor/scalable/apps/NoMercy-MediaServer.png"

        # Create systemd service files
        cat > "${PACKAGE_ROOT}/usr/lib/systemd/user/nomercymediaserver.service" << 'EOF'
        [Unit]
        Description=NoMercy MediaServer
        After=network.target

        [Service]
        Type=simple
        ExecStart=/opt/nomercy/NoMercyMediaServer
        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=default.target
        EOF
        chmod 644 "${PACKAGE_ROOT}/usr/lib/systemd/user/nomercymediaserver.service"

        cat > "${PACKAGE_ROOT}/usr/lib/systemd/user/nomercymediaserverservice.service" << 'EOF'
        [Unit]
        Description=NoMercy MediaServer Service (Tray)
        After=network.target

        [Service]
        Type=simple
        ExecStart=/opt/nomercy/NoMercyMediaServerService
        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=default.target
        EOF
        chmod 644 "${PACKAGE_ROOT}/usr/lib/systemd/user/nomercymediaserverservice.service"

        # Copyright file
        cat > "${PACKAGE_ROOT}/usr/share/doc/nomercy/copyright" << EOF
        Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
        Upstream-Name: NoMercy MediaServer
        Source: https://nomercy.tv

        Files: *
        Copyright: $(date +%Y) NoMercy Entertainment
        License: Proprietary
         This is proprietary software.
         .
         All rights reserved.
        EOF

        # Control file
        cat > "${PACKAGE_ROOT}/DEBIAN/control" << EOF
        Package: nomercy
        Version: ${VERSION}
        Architecture: amd64
        Maintainer: NoMercy Entertainment <support@nomercy.tv>
        Description: NoMercy MediaServer - complete installation
         Modern Media Server Solution with server, tray service, and CLI tool.
        Depends: libc6 (>= 2.31), libgcc-s1, libssl3 | libssl1.1
        Recommends: systemd
        Priority: optional
        Section: multimedia
        EOF

        # postinst
        cat > "${PACKAGE_ROOT}/DEBIAN/postinst" << 'EOF'
        #!/bin/sh
        set -e
        if command -v update-icon-caches >/dev/null 2>&1; then
            update-icon-caches /usr/share/icons/hicolor >/dev/null 2>&1 || true
        fi
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
        fi
        if command -v systemctl >/dev/null 2>&1; then
            systemctl --user daemon-reload >/dev/null 2>&1 || true
        fi
        exit 0
        EOF
        chmod 755 "${PACKAGE_ROOT}/DEBIAN/postinst"

        # prerm
        cat > "${PACKAGE_ROOT}/DEBIAN/prerm" << 'EOF'
        #!/bin/sh
        set -e
        if command -v systemctl >/dev/null 2>&1; then
            systemctl --user stop nomercymediaserver.service >/dev/null 2>&1 || true
            systemctl --user disable nomercymediaserver.service >/dev/null 2>&1 || true
            systemctl --user stop nomercymediaserverservice.service >/dev/null 2>&1 || true
            systemctl --user disable nomercymediaserverservice.service >/dev/null 2>&1 || true
        fi
        exit 0
        EOF
        chmod 755 "${PACKAGE_ROOT}/DEBIAN/prerm"

        # postrm
        cat > "${PACKAGE_ROOT}/DEBIAN/postrm" << 'EOF'
        #!/bin/sh
        set -e
        if [ "$1" = "purge" ]; then
            if command -v update-icon-caches >/dev/null 2>&1; then
                update-icon-caches /usr/share/icons/hicolor >/dev/null 2>&1 || true
            fi
            if command -v update-desktop-database >/dev/null 2>&1; then
                update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
            fi
        fi
        exit 0
        EOF
        chmod 755 "${PACKAGE_ROOT}/DEBIAN/postrm"

        # Build package
        dpkg-deb --build "${PACKAGE_ROOT}"
        mkdir -p "./packages/apt/pool/main/n/nomercy"
        mv "${PACKAGE_ROOT}.deb" "./packages/apt/pool/main/n/nomercy/nomercy_${VERSION}_amd64.deb"
        cd "./packages/apt/pool/main/n/nomercy"
        ln -sf "nomercy_${VERSION}_amd64.deb" "nomercy_latest_amd64.deb"
        cd ../../../../../..
        echo "Successfully created nomercy DEB package"

        # Update package index
        mkdir -p packages/apt/dists/stable/main/binary-amd64
        cd packages/apt
        rm -f dists/stable/main/binary-amd64/Packages*
        dpkg-scanpackages --multiversion pool/ > dists/stable/main/binary-amd64/Packages
        gzip -k -f dists/stable/main/binary-amd64/Packages

    - name: Upload DEB artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-packages
        path: packages/apt/
