// -----------------------------------------------------------------------------
//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.
//
//  This file is part of NoMercy MediaServer, source-available software (NOT open
//  source). Personal use and contributions are welcome; distribution, resale,
//  relicensing, and commercial exploitation are prohibited without explicit
//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.
//
//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary
// -----------------------------------------------------------------------------

using NoMercy.Api.DTOs.Media;
using Xunit;

namespace NoMercy.Tests.Api.Media.Components;

/// <summary>
/// Coverage for the pre-ComponentEnvelope builder pair (ComponentBuilder&lt;T&gt;
/// / ComponentPropsBuilder&lt;T&gt;). Superseded by Component/LeafComponentBuilder
/// in the Components/ subfolder for every live call site, but the type is still
/// public API surface reachable via LoloMoResponseDto&lt;T&gt; wiring, so it is
/// exercised directly here rather than left untested.
/// </summary>
[Trait("Category", "Unit")]
public class ComponentBuilderLegacyTests
{
    [Fact]
    public void WithComponent_SetsComponentName()
    {
        ComponentDto<string> dto = new ComponentBuilder<string>().WithComponent("NMCard").Build();

        dto.Component.Should().Be("NMCard");
    }

    [Fact]
    public void WithId_OverridesTheAutoGeneratedId()
    {
        Ulid explicitId = Ulid.NewUlid();

        ComponentDto<string> dto = new ComponentBuilder<string>().WithId(explicitId).Build();

        dto.Id.Should().Be(explicitId);
    }

    [Fact]
    public void WithReplacing_SetsReplacingId()
    {
        Ulid replacingId = Ulid.NewUlid();

        ComponentDto<string> dto = new ComponentBuilder<string>()
            .WithReplacing(replacingId)
            .Build();

        dto.Replacing.Should().Be(replacingId);
    }

    [Fact]
    public void WithUpdate_NullArgs_LeavesWhenAndLinkUntouched()
    {
        ComponentDto<string> before = new ComponentBuilder<string>().Build();
        string? whenBefore = before.Update.When;

        ComponentDto<string> dto = new ComponentBuilder<string>().WithUpdate().Build();

        dto.Update.When.Should().Be(whenBefore);
    }

    [Fact]
    public void WithUpdate_SetsWhenAndLink()
    {
        ComponentDto<string> dto = new ComponentBuilder<string>()
            .WithUpdate(when: "always", link: "/some/link")
            .Build();

        dto.Update.When.Should().Be("always");
        dto.Update.Link.ToString().Should().Be("/some/link");
    }

    [Fact]
    public void WithUpdate_OnlyWhen_LeavesLinkAsDefault()
    {
        ComponentDto<string> dto = new ComponentBuilder<string>()
            .WithUpdate(when: "always")
            .Build();

        dto.Update.When.Should().Be("always");
    }

    [Fact]
    public void WithProps_PropsBuilderMutatesTheSameComponentInstance()
    {
        ComponentDto<string> dto = new ComponentBuilder<string>()
            .WithProps((props, _) => props.WithTitle("My Title").WithData("payload").WithWatch())
            .Build();

        dto.Props.Title.Should().Be("My Title");
        dto.Props.Data.Should().Be("payload");
        dto.Props.Watch.Should().BeTrue();
    }

    [Fact]
    public void WithProps_PassesTheComponentsOwnIdToTheCallback()
    {
        Ulid? seenId = null;

        ComponentDto<string> dto = new ComponentBuilder<string>()
            .WithProps(
                (_, componentId) =>
                {
                    seenId = componentId;
                }
            )
            .Build();

        seenId.Should().Be(dto.Id);
    }

    // =========================================================================
    // ComponentPropsBuilder<T> — exercised through ComponentBuilder<T>.WithProps,
    // and directly to cover chain members WithProps() never touches.
    // =========================================================================

    [Fact]
    public void PropsBuilder_WithIdNextIdPreviousId_SetAllThreeIds()
    {
        RenderProps<string> props = new();
        Ulid id = Ulid.NewUlid();
        Ulid nextId = Ulid.NewUlid();
        Ulid previousId = Ulid.NewUlid();

        new ComponentPropsBuilder<string>(props)
            .WithId(id)
            .WithNextId(nextId)
            .WithPreviousId(previousId);

        ((Ulid)props.Id).Should().Be(id);
        ((Ulid)props.NextId).Should().Be(nextId);
        ((Ulid)props.PreviousId).Should().Be(previousId);
    }

    [Fact]
    public void PropsBuilder_WithMoreLink_SetsMoreLinkAndDerivedMoreLinkText()
    {
        RenderProps<string> props = new();

        new ComponentPropsBuilder<string>(props).WithMoreLink(new("/more", UriKind.Relative));

        props.MoreLink!.ToString().Should().Be("/more");
        props.MoreText.Should().NotBeNull();
    }

    [Fact]
    public void PropsBuilder_NoMoreLink_MoreLinkTextIsNull()
    {
        RenderProps<string> props = new();

        props.MoreText.Should().BeNull();
    }

    [Fact]
    public void PropsBuilder_WithContextMenuItems_SetsItems()
    {
        RenderProps<string> props = new();
        Dictionary<string, object>[] items = [new() { ["id"] = "remove" }];

        new ComponentPropsBuilder<string>(props).WithContextMenuItems(items);

        props.ContextMenuItems.Should().BeEquivalentTo(items);
    }

    [Fact]
    public void PropsBuilder_WithProperties_SetsPropertiesDictionary()
    {
        RenderProps<string> props = new();
        Dictionary<string, dynamic> properties = new() { ["key"] = "value" };

        new ComponentPropsBuilder<string>(props).WithProperties(properties);

        ((string)props.Properties["key"]).Should().Be("value");
    }

    [Fact]
    public void PropsBuilder_WithItemsGeneric_CastsChildComponentDtosIntoItems()
    {
        RenderProps<string> props = new();
        List<ComponentDto<string>> children =
        [
            new ComponentBuilder<string>().WithComponent("Child").Build(),
        ];

        new ComponentPropsBuilder<string>(props).WithItems<string>(children);

        props.Items.Should().ContainSingle(item => item.Component == "Child");
    }

    [Fact]
    public void PropsBuilder_WithItemsNonGenericOverload_AssignsItemsDirectly()
    {
        RenderProps<string> props = new();
        List<ComponentDto<string>> children =
        [
            new ComponentBuilder<string>().WithComponent("ChildTwo").Build(),
        ];

        new ComponentPropsBuilder<string>(props).WithItems(children);

        props.Items.Should().ContainSingle(item => item.Component == "ChildTwo");
    }

    [Fact]
    public void PropsBuilder_WithWatch_DefaultsToTrue()
    {
        RenderProps<string> props = new();

        new ComponentPropsBuilder<string>(props).WithWatch();

        props.Watch.Should().BeTrue();
    }

    [Fact]
    public void PropsBuilder_WithWatch_ExplicitFalse_ClearsFlag()
    {
        RenderProps<string> props = new() { Watch = true };

        new ComponentPropsBuilder<string>(props).WithWatch(false);

        props.Watch.Should().BeFalse();
    }
}
