#!/bin/sh
set -e

# Reload systemd user daemon to recognize the new service file
systemctl --user daemon-reload || true

# Enable and start the service for the user who ran the installation (using SUDO_USER)
if [ -n "$SUDO_USER" ]; then
su - $SUDO_USER -c "systemctl --user enable nomercymediaserver.service" || true
su - $SUDO_USER -c "systemctl --user start nomercymediaserver.service" || true
fi

exit 0
