#!/bin/sh
set -e

# Stop and disable service
if [ -n "$SUDO_USER" ]; then
su - $SUDO_USER -c "systemctl --user stop nomercyapp.service" || true
su - $SUDO_USER -c "systemctl --user disable nomercyapp.service" || true
fi

exit 0
