<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Product>NoMercy Notifications</Product>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NoMercy.Tests.Notifications" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NoMercy.NmSystem\NoMercy.NmSystem.csproj" />
  </ItemGroup>
</Project>
