// -----------------------------------------------------------------------------
//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.
//
//  This file is part of NoMercy MediaServer, source-available software (NOT open
//  source). Personal use and contributions are welcome; distribution, resale,
//  relicensing, and commercial exploitation are prohibited without explicit
//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.
//
//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary
// -----------------------------------------------------------------------------

// Generated by tools/nm-components. Do not edit.

namespace NoMercy.Design;

/// <summary>
/// Starts a component. Chain from here.
/// </summary>
public static class Nm
{
    /// <summary>Starts a NMAvatar.</summary>
    public static NMAvatarProps Avatar(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMBadge.</summary>
    public static NMBadgeProps Badge(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMDivider.</summary>
    public static NMDividerProps Divider(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMFormLabel.</summary>
    public static NMFormLabelProps FormLabel(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMHelper.</summary>
    public static NMHelperProps Helper(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMImage.</summary>
    public static NMImageProps Image(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMLink.</summary>
    public static NMLinkProps Link(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMProgress.</summary>
    public static NMProgressProps Progress(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMSkeleton.</summary>
    public static NMSkeletonProps Skeleton(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMSpinner.</summary>
    public static NMSpinnerProps Spinner(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMTag.</summary>
    public static NMTagProps Tag(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMButton.</summary>
    public static NMButtonProps Button(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMCheckbox.</summary>
    public static NMCheckboxProps Checkbox(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMInput.</summary>
    public static NMInputProps Input(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMRadio.</summary>
    public static NMRadioProps Radio(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMRating.</summary>
    public static NMRatingProps Rating(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMSlider.</summary>
    public static NMSliderProps Slider(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMTextarea.</summary>
    public static NMTextareaProps Textarea(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMToggle.</summary>
    public static NMToggleProps Toggle(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMBadgeGroup.</summary>
    public static NMBadgeGroupProps BadgeGroup(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMBreadcrumb.</summary>
    public static NMBreadcrumbProps Breadcrumb(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMButtonGroup.</summary>
    public static NMButtonGroupProps ButtonGroup(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMCheckboxGroup.</summary>
    public static NMCheckboxGroupProps CheckboxGroup(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMPagination.</summary>
    public static NMPaginationProps Pagination(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMRadioGroup.</summary>
    public static NMRadioGroupProps RadioGroup(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMSegmented.</summary>
    public static NMSegmentedProps Segmented(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMStepIndicator.</summary>
    public static NMStepIndicatorProps StepIndicator(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMToggles.</summary>
    public static NMTogglesProps Toggles(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMAlert.</summary>
    public static NMAlertProps Alert(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMCard.</summary>
    public static NMCardProps Card(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMChat.</summary>
    public static NMChatProps Chat(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMContentFooter.</summary>
    public static NMContentFooterProps ContentFooter(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMContentHeader.</summary>
    public static NMContentHeaderProps ContentHeader(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMEmptyState.</summary>
    public static NMEmptyStateProps EmptyState(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMList.</summary>
    public static NMListProps List(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMMetrics.</summary>
    public static NMMetricsProps Metrics(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMTable.</summary>
    public static NMTableProps Table(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMColorPicker.</summary>
    public static NMColorPickerProps ColorPicker(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMCombobox.</summary>
    public static NMComboboxProps Combobox(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMCommandPalette.</summary>
    public static NMCommandPaletteProps CommandPalette(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMDatePicker.</summary>
    public static NMDatePickerProps DatePicker(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMDrawer.</summary>
    public static NMDrawerProps Drawer(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMDropdown.</summary>
    public static NMDropdownProps Dropdown(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMModal.</summary>
    public static NMModalProps Modal(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMPopover.</summary>
    public static NMPopoverProps Popover(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMSearchInput.</summary>
    public static NMSearchInputProps SearchInput(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMSelect.</summary>
    public static NMSelectProps Select(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMToast.</summary>
    public static NMToastProps Toast(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMTooltip.</summary>
    public static NMTooltipProps Tooltip(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMAccordion.</summary>
    public static NMAccordionProps Accordion(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMCarousel.</summary>
    public static NMCarouselProps Carousel(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMFileUpload.</summary>
    public static NMFileUploadProps FileUpload(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMNavigation.</summary>
    public static NMNavigationProps Navigation(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMStepper.</summary>
    public static NMStepperProps Stepper(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMTabs.</summary>
    public static NMTabsProps Tabs(string? id = null) =>
        new() { Id = id };

    /// <summary>Starts a NMTreeView.</summary>
    public static NMTreeViewProps TreeView(string? id = null) =>
        new() { Id = id };

}

/// <summary>
/// The setters every component shares.
/// </summary>
public static class NmPropsExtensions
{
    /// <summary>Nests components inside this one, appending to what is there.</summary>
    public static T Add<T>(this T props, params NmComponent[] children) where T : NmProps
    {
        props.Items = [.. props.Items, .. children];
        return props;
    }

    /// <summary>The palette family this component draws its accent from.</summary>
    public static T Color<T>(this T props, string family) where T : NmProps
    {
        props.Color = family;
        return props;
    }

    /// <summary>The box: what the parent owns and what the component owns.</summary>
    public static T Box<T>(this T props, NmBox box) where T : NmProps
    {
        props.Box = box;
        return props;
    }

    /// <summary>Padding on every side, as a key on the spacing scale.</summary>
    public static T Pad<T>(this T props, string space) where T : NmProps
    {
        props.Box ??= new();
        props.Box.Padding = new() { All = space };
        return props;
    }

    /// <summary>Margin on every side, as a key on the spacing scale.</summary>
    public static T Margin<T>(this T props, string space) where T : NmProps
    {
        props.Box ??= new();
        props.Box.Margin = new() { All = space };
        return props;
    }

    /// <summary>Space between the children this component holds.</summary>
    public static T Gap<T>(this T props, string space) where T : NmProps
    {
        props.Box ??= new();
        props.Box.Gap = new() { All = space };
        return props;
    }

    /// <summary>How the component looks: its own surface treatment.</summary>
    public static T Surface<T>(this T props, NmSurface surface) where T : NmProps
    {
        props.Surface = surface;
        return props;
    }

    /// <summary>What happens when the viewer activates this component.</summary>
    public static T Does<T>(this T props, NmAction action) where T : NmProps
    {
        props.Action = action;
        return props;
    }

    /// <summary>What assistive technology announces for this component.</summary>
    public static T Describe<T>(this T props, NmAccessibility accessibility) where T : NmProps
    {
        props.Accessibility = accessibility;
        return props;
    }
}

/// <summary>The setters a NMAvatar adds of its own.</summary>
public static class NMAvatarExtensions
{
    /// <summary>
    /// Alt text for image (required for type="image")
    /// </summary>
    public static NMAvatarProps Alt(this NMAvatarProps props, string value)
    {
        props.Alt = value;
        return props;
    }

    /// <summary>
    /// ARIA Label
    /// </summary>
    public static NMAvatarProps AriaLabel(this NMAvatarProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// The size of the avatar
    /// </summary>
    public static NMAvatarProps Size(this NMAvatarProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Use square shape instead of circular
    /// </summary>
    public static NMAvatarProps Square(this NMAvatarProps props, bool value)
    {
        props.Square = value;
        return props;
    }

    /// <summary>
    /// Image URL (for type="image")
    /// </summary>
    public static NMAvatarProps Src(this NMAvatarProps props, string value)
    {
        props.Src = value;
        return props;
    }

    /// <summary>
    /// Status indicator
    /// </summary>
    public static NMAvatarProps Status(this NMAvatarProps props, string value)
    {
        props.Status = value;
        return props;
    }

    /// <summary>
    /// The type of avatar content
    /// </summary>
    public static NMAvatarProps Type(this NMAvatarProps props, string value)
    {
        props.Type = value;
        return props;
    }

}

/// <summary>The setters a NMBadge adds of its own.</summary>
public static class NMBadgeExtensions
{
    /// <summary>
    /// Show status dot indicator
    /// </summary>
    public static NMBadgeProps Dot(this NMBadgeProps props, bool value)
    {
        props.Dot = value;
        return props;
    }

    /// <summary>
    /// Display mode
    /// </summary>
    public static NMBadgeProps Mode(this NMBadgeProps props, string value)
    {
        props.Mode = value;
        return props;
    }

    /// <summary>
    /// Badge size
    /// </summary>
    public static NMBadgeProps Size(this NMBadgeProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Badge text content
    /// </summary>
    public static NMBadgeProps Text(this NMBadgeProps props, string value)
    {
        props.Text = value;
        return props;
    }

    /// <summary>
    /// Visual style variant
    /// </summary>
    public static NMBadgeProps Variant(this NMBadgeProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMDivider adds of its own.</summary>
public static class NMDividerExtensions
{
    /// <summary>
    /// Text label content
    /// </summary>
    public static NMDividerProps LabelText(this NMDividerProps props, string value)
    {
        props.LabelText = value;
        return props;
    }

    /// <summary>
    /// Line style
    /// </summary>
    public static NMDividerProps Line(this NMDividerProps props, string value)
    {
        props.Line = value;
        return props;
    }

    /// <summary>
    /// Content placement
    /// </summary>
    public static NMDividerProps Placement(this NMDividerProps props, string value)
    {
        props.Placement = value;
        return props;
    }

}

/// <summary>The setters a NMFormLabel adds of its own.</summary>
public static class NMFormLabelExtensions
{
    /// <summary>
    /// Disabled state
    /// </summary>
    public static NMFormLabelProps Disabled(this NMFormLabelProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Show info icon
    /// </summary>
    public static NMFormLabelProps InfoIcon(this NMFormLabelProps props, bool value)
    {
        props.InfoIcon = value;
        return props;
    }

    /// <summary>
    /// Info icon tooltip
    /// </summary>
    public static NMFormLabelProps InfoTooltip(this NMFormLabelProps props, string value)
    {
        props.InfoTooltip = value;
        return props;
    }

    /// <summary>
    /// Label text
    /// </summary>
    public static NMFormLabelProps LabelText(this NMFormLabelProps props, string value)
    {
        props.LabelText = value;
        return props;
    }

    /// <summary>
    /// Label marker type
    /// </summary>
    public static NMFormLabelProps Marker(this NMFormLabelProps props, string value)
    {
        props.Marker = value;
        return props;
    }

    /// <summary>
    /// Custom marker text
    /// </summary>
    public static NMFormLabelProps MarkerText(this NMFormLabelProps props, string value)
    {
        props.MarkerText = value;
        return props;
    }

}

/// <summary>The setters a NMHelper adds of its own.</summary>
public static class NMHelperExtensions
{
    /// <summary>
    /// Helper text content
    /// </summary>
    public static NMHelperProps HelperText(this NMHelperProps props, string value)
    {
        props.HelperText = value;
        return props;
    }

    /// <summary>
    /// Show icon
    /// </summary>
    public static NMHelperProps Icon(this NMHelperProps props, bool value)
    {
        props.Icon = value;
        return props;
    }

    /// <summary>
    /// Icon tooltip text
    /// </summary>
    public static NMHelperProps IconTooltip(this NMHelperProps props, string value)
    {
        props.IconTooltip = value;
        return props;
    }

    /// <summary>
    /// Helper status
    /// </summary>
    public static NMHelperProps Status(this NMHelperProps props, string value)
    {
        props.Status = value;
        return props;
    }

}

/// <summary>The setters a NMImage adds of its own.</summary>
public static class NMImageExtensions
{
    /// <summary>
    /// Alt text for accessibility
    /// </summary>
    public static NMImageProps Alt(this NMImageProps props, string value)
    {
        props.Alt = value;
        return props;
    }

    /// <summary>
    /// Image aspect ratio
    /// </summary>
    public static NMImageProps AspectRatio(this NMImageProps props, string value)
    {
        props.AspectRatio = value;
        return props;
    }

    /// <summary>
    /// Show border
    /// </summary>
    public static NMImageProps Border(this NMImageProps props, bool value)
    {
        props.Border = value;
        return props;
    }

    /// <summary>
    /// Enable hover zoom effect
    /// </summary>
    public static NMImageProps Clickable(this NMImageProps props, bool value)
    {
        props.Clickable = value;
        return props;
    }

    /// <summary>
    /// Object fit behavior
    /// </summary>
    public static NMImageProps Fit(this NMImageProps props, string value)
    {
        props.Fit = value;
        return props;
    }

    /// <summary>
    /// Border radius
    /// </summary>
    public static NMImageProps Rounded(this NMImageProps props, string value)
    {
        props.Rounded = value;
        return props;
    }

    /// <summary>
    /// Shadow elevation
    /// </summary>
    public static NMImageProps Shadow(this NMImageProps props, string value)
    {
        props.Shadow = value;
        return props;
    }

    /// <summary>
    /// Image source URL
    /// </summary>
    public static NMImageProps Src(this NMImageProps props, string value)
    {
        props.Src = value;
        return props;
    }

}

/// <summary>The setters a NMLink adds of its own.</summary>
public static class NMLinkExtensions
{
    /// <summary>
    /// Disable link interaction
    /// </summary>
    public static NMLinkProps Disabled(this NMLinkProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Open in new tab
    /// </summary>
    public static NMLinkProps External(this NMLinkProps props, bool value)
    {
        props.External = value;
        return props;
    }

    /// <summary>
    /// Show icon
    /// </summary>
    public static NMLinkProps Icon(this NMLinkProps props, bool value)
    {
        props.Icon = value;
        return props;
    }

    /// <summary>
    /// Icon position
    /// </summary>
    public static NMLinkProps IconPosition(this NMLinkProps props, string value)
    {
        props.IconPosition = value;
        return props;
    }

    /// <summary>
    /// Link size
    /// </summary>
    public static NMLinkProps Size(this NMLinkProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Link text content
    /// </summary>
    public static NMLinkProps Text(this NMLinkProps props, string value)
    {
        props.Text = value;
        return props;
    }

    /// <summary>
    /// Link visual style
    /// </summary>
    public static NMLinkProps Variant(this NMLinkProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMProgress adds of its own.</summary>
public static class NMProgressExtensions
{
    /// <summary>
    /// Accessible label
    /// </summary>
    public static NMProgressProps AriaLabel(this NMProgressProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// Label position
    /// </summary>
    public static NMProgressProps LabelPos(this NMProgressProps props, string value)
    {
        props.LabelPos = value;
        return props;
    }

    /// <summary>
    /// Track height
    /// </summary>
    public static NMProgressProps Size(this NMProgressProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Progress value (0-100)
    /// </summary>
    public static NMProgressProps Value(this NMProgressProps props, int value)
    {
        props.Value = value;
        return props;
    }

}

/// <summary>The setters a NMSkeleton adds of its own.</summary>
public static class NMSkeletonExtensions
{
    /// <summary>
    /// Skeleton shape
    /// </summary>
    public static NMSkeletonProps Variant(this NMSkeletonProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMSpinner adds of its own.</summary>
public static class NMSpinnerExtensions
{
    /// <summary>
    /// Accessible label
    /// </summary>
    public static NMSpinnerProps AriaLabel(this NMSpinnerProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// Spinner size
    /// </summary>
    public static NMSpinnerProps Size(this NMSpinnerProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMTag adds of its own.</summary>
public static class NMTagExtensions
{
    /// <summary>
    /// Show leading avatar
    /// </summary>
    public static NMTagProps Avatar(this NMTagProps props, bool value)
    {
        props.Avatar = value;
        return props;
    }

    /// <summary>
    /// Show leading checkbox
    /// </summary>
    public static NMTagProps Checkbox(this NMTagProps props, bool value)
    {
        props.Checkbox = value;
        return props;
    }

    /// <summary>
    /// Show count pill
    /// </summary>
    public static NMTagProps Count(this NMTagProps props, bool value)
    {
        props.Count = value;
        return props;
    }

    /// <summary>
    /// Count value
    /// </summary>
    public static NMTagProps CountText(this NMTagProps props, string value)
    {
        props.CountText = value;
        return props;
    }

    /// <summary>
    /// Show leading icon
    /// </summary>
    public static NMTagProps Icon(this NMTagProps props, bool value)
    {
        props.Icon = value;
        return props;
    }

    /// <summary>
    /// Tag size
    /// </summary>
    public static NMTagProps Size(this NMTagProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Tag label text
    /// </summary>
    public static NMTagProps Text(this NMTagProps props, string value)
    {
        props.Text = value;
        return props;
    }

    /// <summary>
    /// Show close button
    /// </summary>
    public static NMTagProps Xclose(this NMTagProps props, bool value)
    {
        props.Xclose = value;
        return props;
    }

}

/// <summary>The setters a NMButton adds of its own.</summary>
public static class NMButtonExtensions
{
    /// <summary>
    /// Accessible label for icon-only buttons
    /// </summary>
    public static NMButtonProps AriaLabel(this NMButtonProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// Whether the button is disabled
    /// </summary>
    public static NMButtonProps Disabled(this NMButtonProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Whether to render as icon-only (hides label)
    /// </summary>
    public static NMButtonProps IconOnly(this NMButtonProps props, bool value)
    {
        props.IconOnly = value;
        return props;
    }

    /// <summary>
    /// Whether the button is in a loading state
    /// </summary>
    public static NMButtonProps Loading(this NMButtonProps props, bool value)
    {
        props.Loading = value;
        return props;
    }

    /// <summary>
    /// The size of the button
    /// </summary>
    public static NMButtonProps Size(this NMButtonProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// The visual style variant of the button
    /// </summary>
    public static NMButtonProps Variant(this NMButtonProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMCheckbox adds of its own.</summary>
public static class NMCheckboxExtensions
{
    /// <summary>
    /// Accessible name, used when there is no labelText
    /// </summary>
    public static NMCheckboxProps AriaLabel(this NMCheckboxProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// Whether the checkbox is checked or indeterminate
    /// </summary>
    public static NMCheckboxProps Checked(this NMCheckboxProps props, string value)
    {
        props.Checked = value;
        return props;
    }

    /// <summary>
    /// Whether the checkbox is disabled
    /// </summary>
    public static NMCheckboxProps Disabled(this NMCheckboxProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Optional helper text below label
    /// </summary>
    public static NMCheckboxProps HelperText(this NMCheckboxProps props, string value)
    {
        props.HelperText = value;
        return props;
    }

    /// <summary>
    /// Optional label text
    /// </summary>
    public static NMCheckboxProps LabelText(this NMCheckboxProps props, string value)
    {
        props.LabelText = value;
        return props;
    }

    /// <summary>
    /// The size of the checkbox
    /// </summary>
    public static NMCheckboxProps Size(this NMCheckboxProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMInput adds of its own.</summary>
public static class NMInputExtensions
{
    /// <summary>
    /// Whether the input is disabled
    /// </summary>
    public static NMInputProps Disabled(this NMInputProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Whether the input has a validation error
    /// </summary>
    public static NMInputProps Error(this NMInputProps props, bool value)
    {
        props.Error = value;
        return props;
    }

    /// <summary>
    /// Leading text value
    /// </summary>
    public static NMInputProps LeadingTextValue(this NMInputProps props, string value)
    {
        props.LeadingTextValue = value;
        return props;
    }

    /// <summary>
    /// Placeholder text shown when empty
    /// </summary>
    public static NMInputProps Placeholder(this NMInputProps props, string value)
    {
        props.Placeholder = value;
        return props;
    }

    /// <summary>
    /// The size of the input field
    /// </summary>
    public static NMInputProps Size(this NMInputProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMRadio adds of its own.</summary>
public static class NMRadioExtensions
{
    /// <summary>
    /// Accessible name, used when there is no labelText
    /// </summary>
    public static NMRadioProps AriaLabel(this NMRadioProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// Whether the radio is selected
    /// </summary>
    public static NMRadioProps Checked(this NMRadioProps props, bool value)
    {
        props.Checked = value;
        return props;
    }

    /// <summary>
    /// Whether the radio is disabled
    /// </summary>
    public static NMRadioProps Disabled(this NMRadioProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Optional helper text below label
    /// </summary>
    public static NMRadioProps HelperText(this NMRadioProps props, string value)
    {
        props.HelperText = value;
        return props;
    }

    /// <summary>
    /// Optional label text
    /// </summary>
    public static NMRadioProps LabelText(this NMRadioProps props, string value)
    {
        props.LabelText = value;
        return props;
    }

    /// <summary>
    /// Group name for mutual exclusivity
    /// </summary>
    public static NMRadioProps Name(this NMRadioProps props, string value)
    {
        props.Name = value;
        return props;
    }

    /// <summary>
    /// The size of the radio button
    /// </summary>
    public static NMRadioProps Size(this NMRadioProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Value submitted with form
    /// </summary>
    public static NMRadioProps Value(this NMRadioProps props, string value)
    {
        props.Value = value;
        return props;
    }

}

/// <summary>The setters a NMRating adds of its own.</summary>
public static class NMRatingExtensions
{
    /// <summary>
    /// Review count shown in parentheses next to label
    /// </summary>
    public static NMRatingProps Count(this NMRatingProps props, int value)
    {
        props.Count = value;
        return props;
    }

    /// <summary>
    /// Disable interaction
    /// </summary>
    public static NMRatingProps Disabled(this NMRatingProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Maximum rating (number of stars)
    /// </summary>
    public static NMRatingProps Max(this NMRatingProps props, string value)
    {
        props.Max = value;
        return props;
    }

    /// <summary>
    /// Read-only display or interactive input
    /// </summary>
    public static NMRatingProps Mode(this NMRatingProps props, string value)
    {
        props.Mode = value;
        return props;
    }

    /// <summary>
    /// Show numeric value label
    /// </summary>
    public static NMRatingProps ShowLabel(this NMRatingProps props, bool value)
    {
        props.ShowLabel = value;
        return props;
    }

    /// <summary>
    /// Star icon size
    /// </summary>
    public static NMRatingProps Size(this NMRatingProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Current rating value (supports 0.5 increments)
    /// </summary>
    public static NMRatingProps Value(this NMRatingProps props, string value)
    {
        props.Value = value;
        return props;
    }

}

/// <summary>The setters a NMSlider adds of its own.</summary>
public static class NMSliderExtensions
{
    /// <summary>
    /// Accessible label
    /// </summary>
    public static NMSliderProps AriaLabel(this NMSliderProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// Disable slider interaction
    /// </summary>
    public static NMSliderProps Disabled(this NMSliderProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Enable range mode with two thumbs
    /// </summary>
    public static NMSliderProps IsBiValue(this NMSliderProps props, bool value)
    {
        props.IsBiValue = value;
        return props;
    }

    /// <summary>
    /// Label display mode
    /// </summary>
    public static NMSliderProps LabelMode(this NMSliderProps props, string value)
    {
        props.LabelMode = value;
        return props;
    }

    /// <summary>
    /// Track height
    /// </summary>
    public static NMSliderProps Size(this NMSliderProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Current value (0-100)
    /// </summary>
    public static NMSliderProps Value(this NMSliderProps props, int value)
    {
        props.Value = value;
        return props;
    }

    /// <summary>
    /// Second value for range mode
    /// </summary>
    public static NMSliderProps Value2(this NMSliderProps props, int value)
    {
        props.Value2 = value;
        return props;
    }

}

/// <summary>The setters a NMTextarea adds of its own.</summary>
public static class NMTextareaExtensions
{
    /// <summary>
    /// Whether the textarea is disabled
    /// </summary>
    public static NMTextareaProps Disabled(this NMTextareaProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Whether the textarea has a validation error
    /// </summary>
    public static NMTextareaProps Error(this NMTextareaProps props, bool value)
    {
        props.Error = value;
        return props;
    }

    /// <summary>
    /// Maximum character limit
    /// </summary>
    public static NMTextareaProps MaxChars(this NMTextareaProps props, int value)
    {
        props.MaxChars = value;
        return props;
    }

    /// <summary>
    /// Placeholder text shown when empty
    /// </summary>
    public static NMTextareaProps Placeholder(this NMTextareaProps props, string value)
    {
        props.Placeholder = value;
        return props;
    }

    /// <summary>
    /// Resize behavior
    /// </summary>
    public static NMTextareaProps Resize(this NMTextareaProps props, string value)
    {
        props.Resize = value;
        return props;
    }

    /// <summary>
    /// Show character counter
    /// </summary>
    public static NMTextareaProps ShowCounter(this NMTextareaProps props, bool value)
    {
        props.ShowCounter = value;
        return props;
    }

    /// <summary>
    /// The size of the textarea
    /// </summary>
    public static NMTextareaProps Size(this NMTextareaProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMToggle adds of its own.</summary>
public static class NMToggleExtensions
{
    /// <summary>
    /// Accessible name, used when there is no labelText
    /// </summary>
    public static NMToggleProps AriaLabel(this NMToggleProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// Whether the switch is on
    /// </summary>
    public static NMToggleProps Checked(this NMToggleProps props, bool value)
    {
        props.Checked = value;
        return props;
    }

    /// <summary>
    /// Whether the switch is disabled
    /// </summary>
    public static NMToggleProps Disabled(this NMToggleProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Optional helper text below label
    /// </summary>
    public static NMToggleProps HelperText(this NMToggleProps props, string value)
    {
        props.HelperText = value;
        return props;
    }

    /// <summary>
    /// Optional label text
    /// </summary>
    public static NMToggleProps LabelText(this NMToggleProps props, string value)
    {
        props.LabelText = value;
        return props;
    }

    /// <summary>
    /// The size of the switch
    /// </summary>
    public static NMToggleProps Size(this NMToggleProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMBadgeGroup adds of its own.</summary>
public static class NMBadgeGroupExtensions
{
    /// <summary>
    /// Badge position relative to text
    /// </summary>
    public static NMBadgeGroupProps BadgePos(this NMBadgeGroupProps props, string value)
    {
        props.BadgePos = value;
        return props;
    }

    /// <summary>
    /// Badge group size
    /// </summary>
    public static NMBadgeGroupProps Size(this NMBadgeGroupProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Badge visual style
    /// </summary>
    public static NMBadgeGroupProps Variant(this NMBadgeGroupProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMBreadcrumb adds of its own.</summary>
public static class NMBreadcrumbExtensions
{
    /// <summary>
    /// Array of breadcrumb labels
    /// </summary>
    public static NMBreadcrumbProps Labels(this NMBreadcrumbProps props, IReadOnlyList<string> value)
    {
        props.Labels = value;
        return props;
    }

    /// <summary>
    /// Separator style
    /// </summary>
    public static NMBreadcrumbProps Separator(this NMBreadcrumbProps props, string value)
    {
        props.Separator = value;
        return props;
    }

}

/// <summary>The setters a NMCheckboxGroup adds of its own.</summary>
public static class NMCheckboxGroupExtensions
{
    /// <summary>
    /// Disabled state for the group
    /// </summary>
    public static NMCheckboxGroupProps GroupDisabled(this NMCheckboxGroupProps props, bool value)
    {
        props.GroupDisabled = value;
        return props;
    }

    /// <summary>
    /// Error state for the group
    /// </summary>
    public static NMCheckboxGroupProps GroupError(this NMCheckboxGroupProps props, bool value)
    {
        props.GroupError = value;
        return props;
    }

    /// <summary>
    /// Layout direction
    /// </summary>
    public static NMCheckboxGroupProps Layout(this NMCheckboxGroupProps props, string value)
    {
        props.Layout = value;
        return props;
    }

    /// <summary>
    /// Checkbox group size
    /// </summary>
    public static NMCheckboxGroupProps Size(this NMCheckboxGroupProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMPagination adds of its own.</summary>
public static class NMPaginationExtensions
{
    /// <summary>
    /// Current page number
    /// </summary>
    public static NMPaginationProps CurrentPage(this NMPaginationProps props, int value)
    {
        props.CurrentPage = value;
        return props;
    }

    /// <summary>
    /// Pagination size
    /// </summary>
    public static NMPaginationProps Size(this NMPaginationProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Total number of pages
    /// </summary>
    public static NMPaginationProps TotalPages(this NMPaginationProps props, int value)
    {
        props.TotalPages = value;
        return props;
    }

}

/// <summary>The setters a NMRadioGroup adds of its own.</summary>
public static class NMRadioGroupExtensions
{
    /// <summary>
    /// Disabled state for the group
    /// </summary>
    public static NMRadioGroupProps GroupDisabled(this NMRadioGroupProps props, bool value)
    {
        props.GroupDisabled = value;
        return props;
    }

    /// <summary>
    /// Error state for the group
    /// </summary>
    public static NMRadioGroupProps GroupError(this NMRadioGroupProps props, bool value)
    {
        props.GroupError = value;
        return props;
    }

    /// <summary>
    /// Layout direction
    /// </summary>
    public static NMRadioGroupProps Layout(this NMRadioGroupProps props, string value)
    {
        props.Layout = value;
        return props;
    }

    /// <summary>
    /// Radio group size
    /// </summary>
    public static NMRadioGroupProps Size(this NMRadioGroupProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMSegmented adds of its own.</summary>
public static class NMSegmentedExtensions
{
    /// <summary>
    /// Disable all segments
    /// </summary>
    public static NMSegmentedProps Disabled(this NMSegmentedProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Expand to full container width
    /// </summary>
    public static NMSegmentedProps FullWidth(this NMSegmentedProps props, bool value)
    {
        props.FullWidth = value;
        return props;
    }

    /// <summary>
    /// Segmented control size
    /// </summary>
    public static NMSegmentedProps Size(this NMSegmentedProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Currently selected value
    /// </summary>
    public static NMSegmentedProps Value(this NMSegmentedProps props, string value)
    {
        props.Value = value;
        return props;
    }

}

/// <summary>The setters a NMStepIndicator adds of its own.</summary>
public static class NMStepIndicatorExtensions
{
    /// <summary>
    /// Zero-based index of current step
    /// </summary>
    public static NMStepIndicatorProps ActiveIndex(this NMStepIndicatorProps props, string value)
    {
        props.ActiveIndex = value;
        return props;
    }

    /// <summary>
    /// Indicator size
    /// </summary>
    public static NMStepIndicatorProps Size(this NMStepIndicatorProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Total number of steps
    /// </summary>
    public static NMStepIndicatorProps Steps(this NMStepIndicatorProps props, string value)
    {
        props.Steps = value;
        return props;
    }

    /// <summary>
    /// Visual variant
    /// </summary>
    public static NMStepIndicatorProps Variant(this NMStepIndicatorProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMToggles adds of its own.</summary>
public static class NMTogglesExtensions
{
    /// <summary>
    /// Disabled state
    /// </summary>
    public static NMTogglesProps Disabled(this NMTogglesProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Toggle size
    /// </summary>
    public static NMTogglesProps Size(this NMTogglesProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Toggle state
    /// </summary>
    public static NMTogglesProps State(this NMTogglesProps props, string value)
    {
        props.State = value;
        return props;
    }

    /// <summary>
    /// Toggle type
    /// </summary>
    public static NMTogglesProps Type(this NMTogglesProps props, string value)
    {
        props.Type = value;
        return props;
    }

}

/// <summary>The setters a NMAlert adds of its own.</summary>
public static class NMAlertExtensions
{
    /// <summary>
    /// Show close button
    /// </summary>
    public static NMAlertProps Closable(this NMAlertProps props, bool value)
    {
        props.Closable = value;
        return props;
    }

    /// <summary>
    /// Enable glow effect (accent style only)
    /// </summary>
    public static NMAlertProps Glow(this NMAlertProps props, bool value)
    {
        props.Glow = value;
        return props;
    }

    /// <summary>
    /// Semantic severity level
    /// </summary>
    public static NMAlertProps Severity(this NMAlertProps props, string value)
    {
        props.Severity = value;
        return props;
    }

    /// <summary>
    /// Alert size
    /// </summary>
    public static NMAlertProps Size(this NMAlertProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Visual style
    /// </summary>
    public static NMAlertProps Style(this NMAlertProps props, string value)
    {
        props.Style = value;
        return props;
    }

}

/// <summary>The setters a NMCard adds of its own.</summary>
public static class NMCardExtensions
{
    /// <summary>
    /// Footer variant
    /// </summary>
    public static NMCardProps FooterVariant(this NMCardProps props, string value)
    {
        props.FooterVariant = value;
        return props;
    }

    /// <summary>
    /// Internal padding size
    /// </summary>
    public static NMCardProps Padding(this NMCardProps props, string value)
    {
        props.Padding = value;
        return props;
    }

    /// <summary>
    /// Card visual style
    /// </summary>
    public static NMCardProps Variant(this NMCardProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMChat adds of its own.</summary>
public static class NMChatExtensions
{
    /// <summary>
    /// Array of message objects
    /// </summary>
    public static NMChatProps Messages(this NMChatProps props, IReadOnlyList<NmChatMessage> value)
    {
        props.Messages = value;
        return props;
    }

}

/// <summary>The setters a NMContentFooter adds of its own.</summary>
public static class NMContentFooterExtensions
{
    /// <summary>
    /// Footer variant
    /// </summary>
    public static NMContentFooterProps Variant(this NMContentFooterProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMContentHeader adds of its own.</summary>
public static class NMContentHeaderExtensions
{
    /// <summary>
    /// Show close button
    /// </summary>
    public static NMContentHeaderProps CanClose(this NMContentHeaderProps props, bool value)
    {
        props.CanClose = value;
        return props;
    }

    /// <summary>
    /// id put on the title, for a dialog to reference with aria-labelledby
    /// </summary>
    public static NMContentHeaderProps TitleId(this NMContentHeaderProps props, string value)
    {
        props.TitleId = value;
        return props;
    }

}

/// <summary>The setters a NMEmptyState adds of its own.</summary>
public static class NMEmptyStateExtensions
{
    /// <summary>
    /// Empty state layout variant
    /// </summary>
    public static NMEmptyStateProps Variant(this NMEmptyStateProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMList adds of its own.</summary>
public static class NMListExtensions
{
    /// <summary>
    /// Bullet style for unordered lists
    /// </summary>
    public static NMListProps Bullet(this NMListProps props, string value)
    {
        props.Bullet = value;
        return props;
    }

    /// <summary>
    /// Horizontal layout
    /// </summary>
    public static NMListProps Horizontal(this NMListProps props, bool value)
    {
        props.Horizontal = value;
        return props;
    }

    /// <summary>
    /// Numbering style for ordered lists
    /// </summary>
    public static NMListProps Order(this NMListProps props, string value)
    {
        props.Order = value;
        return props;
    }

    /// <summary>
    /// List size
    /// </summary>
    public static NMListProps Size(this NMListProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// List type
    /// </summary>
    public static NMListProps Type(this NMListProps props, string value)
    {
        props.Type = value;
        return props;
    }

}

/// <summary>The setters a NMMetrics adds of its own.</summary>
public static class NMMetricsExtensions
{
    /// <summary>
    /// Change indicator
    /// </summary>
    public static NMMetricsProps Change(this NMMetricsProps props, string value)
    {
        props.Change = value;
        return props;
    }

    /// <summary>
    /// Metric label
    /// </summary>
    public static NMMetricsProps Label(this NMMetricsProps props, string value)
    {
        props.Label = value;
        return props;
    }

    /// <summary>
    /// Show decorative icon
    /// </summary>
    public static NMMetricsProps ShowIcon(this NMMetricsProps props, bool value)
    {
        props.ShowIcon = value;
        return props;
    }

    /// <summary>
    /// Trend direction
    /// </summary>
    public static NMMetricsProps Trend(this NMMetricsProps props, string value)
    {
        props.Trend = value;
        return props;
    }

    /// <summary>
    /// Metric value
    /// </summary>
    public static NMMetricsProps Value(this NMMetricsProps props, string value)
    {
        props.Value = value;
        return props;
    }

    /// <summary>
    /// Metric visual style
    /// </summary>
    public static NMMetricsProps Variant(this NMMetricsProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMTable adds of its own.</summary>
public static class NMTableExtensions
{
    /// <summary>
    /// Array of column definitions
    /// </summary>
    public static NMTableProps Columns(this NMTableProps props, IReadOnlyList<NmTableColumn> value)
    {
        props.Columns = value;
        return props;
    }

    /// <summary>
    /// Row hover effect
    /// </summary>
    public static NMTableProps Hover(this NMTableProps props, bool value)
    {
        props.Hover = value;
        return props;
    }

    /// <summary>
    /// Array of row data
    /// </summary>
    public static NMTableProps Rows(this NMTableProps props, IReadOnlyList<NmTableRow> value)
    {
        props.Rows = value;
        return props;
    }

    /// <summary>
    /// Table size
    /// </summary>
    public static NMTableProps Size(this NMTableProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Alternate row background colors
    /// </summary>
    public static NMTableProps Striped(this NMTableProps props, bool value)
    {
        props.Striped = value;
        return props;
    }

    /// <summary>
    /// Table visual style
    /// </summary>
    public static NMTableProps Variant(this NMTableProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMColorPicker adds of its own.</summary>
public static class NMColorPickerExtensions
{
    /// <summary>
    /// Disable the swatch trigger
    /// </summary>
    public static NMColorPickerProps Disabled(this NMColorPickerProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Optional label text above the swatch
    /// </summary>
    public static NMColorPickerProps Label(this NMColorPickerProps props, string value)
    {
        props.Label = value;
        return props;
    }

    /// <summary>
    /// Current hex colour value
    /// </summary>
    public static NMColorPickerProps Selected(this NMColorPickerProps props, string value)
    {
        props.Selected = value;
        return props;
    }

    /// <summary>
    /// Show hex input row in panel
    /// </summary>
    public static NMColorPickerProps ShowInput(this NMColorPickerProps props, bool value)
    {
        props.ShowInput = value;
        return props;
    }

    /// <summary>
    /// Show the colour picker panel
    /// </summary>
    public static NMColorPickerProps ShowPanel(this NMColorPickerProps props, bool value)
    {
        props.ShowPanel = value;
        return props;
    }

    /// <summary>
    /// Trigger and palette option size
    /// </summary>
    public static NMColorPickerProps Size(this NMColorPickerProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMCombobox adds of its own.</summary>
public static class NMComboboxExtensions
{
    /// <summary>
    /// Current filter / typed text
    /// </summary>
    public static NMComboboxProps FilterText(this NMComboboxProps props, string value)
    {
        props.FilterText = value;
        return props;
    }

    /// <summary>
    /// Show spinner instead of chevron
    /// </summary>
    public static NMComboboxProps IsLoading(this NMComboboxProps props, bool value)
    {
        props.IsLoading = value;
        return props;
    }

    /// <summary>
    /// Enable multi-select tag mode
    /// </summary>
    public static NMComboboxProps Multiple(this NMComboboxProps props, bool value)
    {
        props.Multiple = value;
        return props;
    }

    /// <summary>
    /// Input placeholder text
    /// </summary>
    public static NMComboboxProps Placeholder(this NMComboboxProps props, string value)
    {
        props.Placeholder = value;
        return props;
    }

    /// <summary>
    /// Currently selected option (single-select mode)
    /// </summary>
    public static NMComboboxProps Selected(this NMComboboxProps props, string value)
    {
        props.Selected = value;
        return props;
    }

    /// <summary>
    /// Currently selected options (multi-select mode)
    /// </summary>
    public static NMComboboxProps SelectedItems(this NMComboboxProps props, IReadOnlyList<string> value)
    {
        props.SelectedItems = value;
        return props;
    }

    /// <summary>
    /// Field and option item size
    /// </summary>
    public static NMComboboxProps Size(this NMComboboxProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMCommandPalette adds of its own.</summary>
public static class NMCommandPaletteExtensions
{
    /// <summary>
    /// Search input value
    /// </summary>
    public static NMCommandPaletteProps SearchText(this NMCommandPaletteProps props, string value)
    {
        props.SearchText = value;
        return props;
    }

}

/// <summary>The setters a NMDatePicker adds of its own.</summary>
public static class NMDatePickerExtensions
{
    /// <summary>
    /// Date picker mode
    /// </summary>
    public static NMDatePickerProps Mode(this NMDatePickerProps props, string value)
    {
        props.Mode = value;
        return props;
    }

    /// <summary>
    /// Calendar size
    /// </summary>
    public static NMDatePickerProps Size(this NMDatePickerProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMDrawer adds of its own.</summary>
public static class NMDrawerExtensions
{
    /// <summary>
    /// Show backdrop overlay
    /// </summary>
    public static NMDrawerProps HasOverlay(this NMDrawerProps props, bool value)
    {
        props.HasOverlay = value;
        return props;
    }

    /// <summary>
    /// Open
    /// </summary>
    public static NMDrawerProps IsOpen(this NMDrawerProps props, bool value)
    {
        props.IsOpen = value;
        return props;
    }

    /// <summary>
    /// Edge to anchor the drawer
    /// </summary>
    public static NMDrawerProps Position(this NMDrawerProps props, string value)
    {
        props.Position = value;
        return props;
    }

    /// <summary>
    /// Drawer width (left/right) or height (top/bottom)
    /// </summary>
    public static NMDrawerProps Size(this NMDrawerProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMDropdown adds of its own.</summary>
public static class NMDropdownExtensions
{
    /// <summary>
    /// Dropdown size
    /// </summary>
    public static NMDropdownProps Size(this NMDropdownProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMModal adds of its own.</summary>
public static class NMModalExtensions
{
    /// <summary>
    /// Footer variant
    /// </summary>
    public static NMModalProps FooterVariant(this NMModalProps props, string value)
    {
        props.FooterVariant = value;
        return props;
    }

    /// <summary>
    /// Modal width
    /// </summary>
    public static NMModalProps Size(this NMModalProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMPopover adds of its own.</summary>
public static class NMPopoverExtensions
{
    /// <summary>
    /// Open
    /// </summary>
    public static NMPopoverProps IsOpen(this NMPopoverProps props, bool value)
    {
        props.IsOpen = value;
        return props;
    }

    /// <summary>
    /// Popover position relative to trigger
    /// </summary>
    public static NMPopoverProps Position(this NMPopoverProps props, string value)
    {
        props.Position = value;
        return props;
    }

    /// <summary>
    /// Show arrow pointing to trigger
    /// </summary>
    public static NMPopoverProps ShowArrow(this NMPopoverProps props, bool value)
    {
        props.ShowArrow = value;
        return props;
    }

    /// <summary>
    /// Show close button
    /// </summary>
    public static NMPopoverProps ShowClose(this NMPopoverProps props, bool value)
    {
        props.ShowClose = value;
        return props;
    }

    /// <summary>
    /// Popover panel width
    /// </summary>
    public static NMPopoverProps Size(this NMPopoverProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMSearchInput adds of its own.</summary>
public static class NMSearchInputExtensions
{
    /// <summary>
    /// Placeholder text
    /// </summary>
    public static NMSearchInputProps Placeholder(this NMSearchInputProps props, string value)
    {
        props.Placeholder = value;
        return props;
    }

    /// <summary>
    /// Field height and font size
    /// </summary>
    public static NMSearchInputProps Size(this NMSearchInputProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Current input value — shows clear button when non-empty
    /// </summary>
    public static NMSearchInputProps Value(this NMSearchInputProps props, string value)
    {
        props.Value = value;
        return props;
    }

}

/// <summary>The setters a NMSelect adds of its own.</summary>
public static class NMSelectExtensions
{
    /// <summary>
    /// Whether the select is disabled
    /// </summary>
    public static NMSelectProps Disabled(this NMSelectProps props, bool value)
    {
        props.Disabled = value;
        return props;
    }

    /// <summary>
    /// Whether the select has a validation error
    /// </summary>
    public static NMSelectProps Error(this NMSelectProps props, bool value)
    {
        props.Error = value;
        return props;
    }

    /// <summary>
    /// Array of selectable options
    /// </summary>
    public static NMSelectProps Options(this NMSelectProps props, IReadOnlyList<NmSelectOption> value)
    {
        props.Options = value;
        return props;
    }

    /// <summary>
    /// Placeholder text shown when no option is selected
    /// </summary>
    public static NMSelectProps Placeholder(this NMSelectProps props, string value)
    {
        props.Placeholder = value;
        return props;
    }

    /// <summary>
    /// The size of the select field
    /// </summary>
    public static NMSelectProps Size(this NMSelectProps props, string value)
    {
        props.Size = value;
        return props;
    }

}

/// <summary>The setters a NMToast adds of its own.</summary>
public static class NMToastExtensions
{
    /// <summary>
    /// Show close button
    /// </summary>
    public static NMToastProps Closable(this NMToastProps props, bool value)
    {
        props.Closable = value;
        return props;
    }

    /// <summary>
    /// Auto-dismiss duration (ms)
    /// </summary>
    public static NMToastProps Duration(this NMToastProps props, int value)
    {
        props.Duration = value;
        return props;
    }

    /// <summary>
    /// Toast message
    /// </summary>
    public static NMToastProps Message(this NMToastProps props, string value)
    {
        props.Message = value;
        return props;
    }

    /// <summary>
    /// Screen position
    /// </summary>
    public static NMToastProps Position(this NMToastProps props, string value)
    {
        props.Position = value;
        return props;
    }

    /// <summary>
    /// Show action button
    /// </summary>
    public static NMToastProps ShowAction(this NMToastProps props, bool value)
    {
        props.ShowAction = value;
        return props;
    }

    /// <summary>
    /// Show variant icon
    /// </summary>
    public static NMToastProps ShowIcon(this NMToastProps props, bool value)
    {
        props.ShowIcon = value;
        return props;
    }

    /// <summary>
    /// Show progress bar
    /// </summary>
    public static NMToastProps ShowProgress(this NMToastProps props, bool value)
    {
        props.ShowProgress = value;
        return props;
    }

    /// <summary>
    /// Toast title
    /// </summary>
    public static NMToastProps Title(this NMToastProps props, string value)
    {
        props.Title = value;
        return props;
    }

    /// <summary>
    /// Toast variant
    /// </summary>
    public static NMToastProps Variant(this NMToastProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMTooltip adds of its own.</summary>
public static class NMTooltipExtensions
{
    /// <summary>
    /// Tooltip position relative to trigger
    /// </summary>
    public static NMTooltipProps Position(this NMTooltipProps props, string value)
    {
        props.Position = value;
        return props;
    }

}

/// <summary>The setters a NMAccordion adds of its own.</summary>
public static class NMAccordionExtensions
{
    /// <summary>
    /// Allow Multiple Open
    /// </summary>
    public static NMAccordionProps AllowMultiple(this NMAccordionProps props, bool value)
    {
        props.AllowMultiple = value;
        return props;
    }

    /// <summary>
    /// Array of content for each item
    /// </summary>
    public static NMAccordionProps Content(this NMAccordionProps props, IReadOnlyList<string> value)
    {
        props.Content = value;
        return props;
    }

    /// <summary>
    /// Object mapping item indices to disabled state
    /// </summary>
    public static NMAccordionProps DisabledItems(this NMAccordionProps props, IReadOnlyDictionary<string, bool> value)
    {
        props.DisabledItems = value;
        return props;
    }

    /// <summary>
    /// Object mapping item indices to open state
    /// </summary>
    public static NMAccordionProps OpenItems(this NMAccordionProps props, IReadOnlyDictionary<string, bool> value)
    {
        props.OpenItems = value;
        return props;
    }

    /// <summary>
    /// Show chevron indicator
    /// </summary>
    public static NMAccordionProps ShowChevron(this NMAccordionProps props, bool value)
    {
        props.ShowChevron = value;
        return props;
    }

    /// <summary>
    /// Accordion size
    /// </summary>
    public static NMAccordionProps Size(this NMAccordionProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Accordion visual style
    /// </summary>
    public static NMAccordionProps Variant(this NMAccordionProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMCarousel adds of its own.</summary>
public static class NMCarouselExtensions
{
    /// <summary>
    /// Position nav arrows outside viewport
    /// </summary>
    public static NMCarouselProps NavOutside(this NMCarouselProps props, bool value)
    {
        props.NavOutside = value;
        return props;
    }

    /// <summary>
    /// Show dot pagination
    /// </summary>
    public static NMCarouselProps ShowDots(this NMCarouselProps props, bool value)
    {
        props.ShowDots = value;
        return props;
    }

    /// <summary>
    /// Show navigation arrows
    /// </summary>
    public static NMCarouselProps ShowNav(this NMCarouselProps props, bool value)
    {
        props.ShowNav = value;
        return props;
    }

    /// <summary>
    /// Carousel size
    /// </summary>
    public static NMCarouselProps Size(this NMCarouselProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Enable scroll snap
    /// </summary>
    public static NMCarouselProps Snap(this NMCarouselProps props, bool value)
    {
        props.Snap = value;
        return props;
    }

}

/// <summary>The setters a NMFileUpload adds of its own.</summary>
public static class NMFileUploadExtensions
{
    /// <summary>
    /// File metadata
    /// </summary>
    public static NMFileUploadProps FileMeta(this NMFileUploadProps props, string value)
    {
        props.FileMeta = value;
        return props;
    }

    /// <summary>
    /// File name
    /// </summary>
    public static NMFileUploadProps FileName(this NMFileUploadProps props, string value)
    {
        props.FileName = value;
        return props;
    }

    /// <summary>
    /// Upload progress percentage
    /// </summary>
    public static NMFileUploadProps UploadPct(this NMFileUploadProps props, int value)
    {
        props.UploadPct = value;
        return props;
    }

}

/// <summary>The setters a NMNavigation adds of its own.</summary>
public static class NMNavigationExtensions
{
    /// <summary>
    /// Currently active item index
    /// </summary>
    public static NMNavigationProps ActiveIndex(this NMNavigationProps props, string value)
    {
        props.ActiveIndex = value;
        return props;
    }

    /// <summary>
    /// Navigation layout style
    /// </summary>
    public static NMNavigationProps Variant(this NMNavigationProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMStepper adds of its own.</summary>
public static class NMStepperExtensions
{
    /// <summary>
    /// Zero-based index of the current active step
    /// </summary>
    public static NMStepperProps ActiveIndex(this NMStepperProps props, string value)
    {
        props.ActiveIndex = value;
        return props;
    }

    /// <summary>
    /// Layout direction
    /// </summary>
    public static NMStepperProps Orientation(this NMStepperProps props, string value)
    {
        props.Orientation = value;
        return props;
    }

    /// <summary>
    /// Circle and text size
    /// </summary>
    public static NMStepperProps Size(this NMStepperProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Array of step objects with label and optional description
    /// </summary>
    public static NMStepperProps Steps(this NMStepperProps props, IReadOnlyList<NmStep> value)
    {
        props.Steps = value;
        return props;
    }

}

/// <summary>The setters a NMTabs adds of its own.</summary>
public static class NMTabsExtensions
{
    /// <summary>
    /// Currently active tab index
    /// </summary>
    public static NMTabsProps ActiveIndex(this NMTabsProps props, string value)
    {
        props.ActiveIndex = value;
        return props;
    }

    /// <summary>
    /// Accessible name for the tablist
    /// </summary>
    public static NMTabsProps AriaLabel(this NMTabsProps props, string value)
    {
        props.AriaLabel = value;
        return props;
    }

    /// <summary>
    /// Tab size
    /// </summary>
    public static NMTabsProps Size(this NMTabsProps props, string value)
    {
        props.Size = value;
        return props;
    }

    /// <summary>
    /// Array of tab labels
    /// </summary>
    public static NMTabsProps TabLabels(this NMTabsProps props, IReadOnlyList<string> value)
    {
        props.TabLabels = value;
        return props;
    }

    /// <summary>
    /// Base id for the tabs. Pass one and each tab gets
    /// aria-controls="{tablistId}-panel-{index}", which is the id your panel
    /// needs
    /// </summary>
    public static NMTabsProps TablistId(this NMTabsProps props, string value)
    {
        props.TablistId = value;
        return props;
    }

    /// <summary>
    /// Tab visual style
    /// </summary>
    public static NMTabsProps Variant(this NMTabsProps props, string value)
    {
        props.Variant = value;
        return props;
    }

}

/// <summary>The setters a NMTreeView adds of its own.</summary>
public static class NMTreeViewExtensions
{
    /// <summary>
    /// Show vertical indent guide lines
    /// </summary>
    public static NMTreeViewProps ShowLines(this NMTreeViewProps props, bool value)
    {
        props.ShowLines = value;
        return props;
    }

    /// <summary>
    /// Row spacing and icon size
    /// </summary>
    public static NMTreeViewProps Size(this NMTreeViewProps props, string value)
    {
        props.Size = value;
        return props;
    }

}
