// -----------------------------------------------------------------------------
//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.
//
//  This file is part of NoMercy MediaServer, source-available software (NOT open
//  source). Personal use and contributions are welcome; distribution, resale,
//  relicensing, and commercial exploitation are prohibited without explicit
//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.
//
//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary
// -----------------------------------------------------------------------------

// Generated by tools/nm-components from openapi-nm-design-system.yaml.
// Do not edit.

using Newtonsoft.Json;

namespace NoMercy.Design;

/// <summary>
/// A key on the spacing scale. The scale is the design system's, so a key
/// that is not on it is a payload error rather than something the client
/// should try to interpret.
/// </summary>
public static class NmSpace
{
    public const string X0 = "0";
    public const string Px = "px";
    public const string X0_5 = "0-5";
    public const string X1 = "1";
    public const string X1_5 = "1-5";
    public const string X2 = "2";
    public const string X2_5 = "2-5";
    public const string X3 = "3";
    public const string X3_5 = "3-5";
    public const string X4 = "4";
    public const string X4_5 = "4-5";
    public const string X5 = "5";
    public const string X6 = "6";
    public const string X7 = "7";
    public const string X8 = "8";
    public const string X9 = "9";
    public const string X10 = "10";
    public const string X11 = "11";
    public const string X12 = "12";
    public const string X14 = "14";
    public const string X15 = "15";
    public const string X16 = "16";
    public const string X20 = "20";
    public const string X24 = "24";
    public const string X28 = "28";
    public const string X32 = "32";
    public const string X36 = "36";
    public const string X40 = "40";
    public const string X44 = "44";
    public const string X48 = "48";
    public const string X52 = "52";
    public const string X56 = "56";
    public const string X60 = "60";
    public const string X64 = "64";
    public const string X72 = "72";
    public const string X80 = "80";
    public const string X96 = "96";
}

/// <summary>
/// Alignment across the axis that runs against the layout direction.
/// </summary>
public static class NmAlign
{
    public const string Start = "start";
    public const string Center = "center";
    public const string End = "end";
    public const string Stretch = "stretch";
    public const string Baseline = "baseline";
}

/// <summary>
/// Distribution along the layout direction.
/// </summary>
public static class NmJustify
{
    public const string Start = "start";
    public const string Center = "center";
    public const string End = "end";
    public const string Between = "between";
    public const string Around = "around";
    public const string Evenly = "evenly";
}

/// <summary>
/// The axis children flow along. `row` and `column` are resolved against
/// the reading direction, so a right-to-left locale reverses `row` without
/// the payload saying anything about it.
/// </summary>
public static class NmDirection
{
    public const string Row = "row";
    public const string Column = "column";
    public const string RowReverse = "row-reverse";
    public const string ColumnReverse = "column-reverse";
}

public static class NmWrap
{
    public const string Nowrap = "nowrap";
    public const string Wrap = "wrap";
    public const string WrapReverse = "wrap-reverse";
}

/// <summary>
/// What happens to children that do not fit. `scroll` on a tv surface means
/// the container scrolls to follow focus, since there is no pointer to drag
/// it with.
/// </summary>
public static class NmOverflow
{
    public const string Visible = "visible";
    public const string Hidden = "hidden";
    public const string Scroll = "scroll";
    public const string Clip = "clip";
}

public static class NmPosition
{
    public const string Static = "static";
    public const string Relative = "relative";
    public const string Absolute = "absolute";
    public const string Sticky = "sticky";
    public const string Fixed = "fixed";
}

/// <summary>
/// Stacking order, named rather than numbered. A payload that could set a
/// raw z-index would eventually set one that beats the player chrome, so
/// the vocabulary is closed on purpose.
/// </summary>
public static class NmLayer
{
    public const string Base = "base";
    public const string Raised = "raised";
    public const string Sticky = "sticky";
    public const string Overlay = "overlay";
    public const string Modal = "modal";
    public const string Toast = "toast";
    public const string Tooltip = "tooltip";
}

/// <summary>
/// A rendering surface, used to vary or suppress a component per platform.
/// </summary>
public static class NmSurfaceKind
{
    public const string Web = "web";
    public const string Mobile = "mobile";
    public const string Tv = "tv";
}

/// <summary>
/// A spacing value, expressed per side. Resolution runs from the most
/// general to the most specific: `all`, then `x` and `y`, then a named
/// side. A later value replaces an earlier one for the side it names. Every
/// value is a key on the spacing scale, not a length. `"4"` means the
/// scale's step 4, which the client resolves to its own unit. Writing a
/// length here is not supported, because a length cannot survive the trip
/// to a platform whose unit is not the one it was written in.
/// </summary>
public record NmSpacing
{
    [JsonProperty("all", NullValueHandling = NullValueHandling.Ignore)]
    public string? All { get; set; }

    [JsonProperty("x", NullValueHandling = NullValueHandling.Ignore)]
    public string? X { get; set; }

    [JsonProperty("y", NullValueHandling = NullValueHandling.Ignore)]
    public string? Y { get; set; }

    [JsonProperty("top", NullValueHandling = NullValueHandling.Ignore)]
    public string? Top { get; set; }

    [JsonProperty("right", NullValueHandling = NullValueHandling.Ignore)]
    public string? Right { get; set; }

    [JsonProperty("bottom", NullValueHandling = NullValueHandling.Ignore)]
    public string? Bottom { get; set; }

    [JsonProperty("left", NullValueHandling = NullValueHandling.Ignore)]
    public string? Left { get; set; }

}

/// <summary>
/// The space between children, which can differ along each axis. `all` sets
/// both; `x` and `y` override it per axis.
/// </summary>
public record NmGap
{
    [JsonProperty("all", NullValueHandling = NullValueHandling.Ignore)]
    public string? All { get; set; }

    [JsonProperty("x", NullValueHandling = NullValueHandling.Ignore)]
    public string? X { get; set; }

    [JsonProperty("y", NullValueHandling = NullValueHandling.Ignore)]
    public string? Y { get; set; }

}

/// <summary>
/// Geometry, split by who owns it. The outer group is what a parent decides
/// about this component: its margin, how it flexes, how it aligns itself,
/// how many columns it spans, how big it is. A parent sets these on a child
/// it is placing. The inner group is what this component decides about its
/// own children: padding, gap, direction, alignment. A component sets these
/// on itself. Both groups are optional and both are overridable by the
/// payload. The rule that makes this reliable is not in the shape of this
/// object, it is in the order the client applies it: a value from the
/// payload is applied after the component's own default, so the payload
/// always wins. A client that resolves them in the other order will look
/// correct until the first time a parent tries to override a child, which
/// is the failure that would otherwise ship silently.
/// </summary>
public record NmBox
{
    [JsonProperty("margin", NullValueHandling = NullValueHandling.Ignore)]
    public NmSpacing? Margin { get; set; }

    [JsonProperty("width", NullValueHandling = NullValueHandling.Ignore)]
    public string? Width { get; set; }

    [JsonProperty("height", NullValueHandling = NullValueHandling.Ignore)]
    public string? Height { get; set; }

    [JsonProperty("min_width", NullValueHandling = NullValueHandling.Ignore)]
    public string? MinWidth { get; set; }

    [JsonProperty("max_width", NullValueHandling = NullValueHandling.Ignore)]
    public string? MaxWidth { get; set; }

    [JsonProperty("min_height", NullValueHandling = NullValueHandling.Ignore)]
    public string? MinHeight { get; set; }

    [JsonProperty("max_height", NullValueHandling = NullValueHandling.Ignore)]
    public string? MaxHeight { get; set; }

    /// <summary>
    /// How much of the leftover space along the parent's axis this takes.
    /// </summary>
    [JsonProperty("grow", NullValueHandling = NullValueHandling.Ignore)]
    public int? Grow { get; set; }

    /// <summary>
    /// How readily this gives up space when the parent runs short.
    /// </summary>
    [JsonProperty("shrink", NullValueHandling = NullValueHandling.Ignore)]
    public int? Shrink { get; set; }

    [JsonProperty("basis", NullValueHandling = NullValueHandling.Ignore)]
    public string? Basis { get; set; }

    [JsonProperty("align_self", NullValueHandling = NullValueHandling.Ignore)]
    public string? AlignSelf { get; set; }

    /// <summary>
    /// Visual position among siblings, independent of payload order.
    /// </summary>
    [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
    public int? Order { get; set; }

    /// <summary>
    /// Columns this occupies when the parent is a grid.
    /// </summary>
    [JsonProperty("column_span", NullValueHandling = NullValueHandling.Ignore)]
    public int? ColumnSpan { get; set; }

    /// <summary>
    /// Rows this occupies when the parent is a grid.
    /// </summary>
    [JsonProperty("row_span", NullValueHandling = NullValueHandling.Ignore)]
    public int? RowSpan { get; set; }

    [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
    public string? Position { get; set; }

    [JsonProperty("inset", NullValueHandling = NullValueHandling.Ignore)]
    public NmSpacing? Inset { get; set; }

    [JsonProperty("layer", NullValueHandling = NullValueHandling.Ignore)]
    public string? Layer { get; set; }

    /// <summary>
    /// Surfaces this component is not rendered on at all. A component hidden on
    /// tv is never focusable there, which is different from a component that is
    /// merely invisible, and is what D-pad traversal needs.
    /// </summary>
    [JsonProperty("hidden_on")]
    public List<string> HiddenOn { get; set; } = [];

    [JsonProperty("padding", NullValueHandling = NullValueHandling.Ignore)]
    public NmSpacing? Padding { get; set; }

    [JsonProperty("gap", NullValueHandling = NullValueHandling.Ignore)]
    public NmGap? Gap { get; set; }

    [JsonProperty("direction", NullValueHandling = NullValueHandling.Ignore)]
    public string? Direction { get; set; }

    [JsonProperty("align", NullValueHandling = NullValueHandling.Ignore)]
    public string? Align { get; set; }

    [JsonProperty("justify", NullValueHandling = NullValueHandling.Ignore)]
    public string? Justify { get; set; }

    [JsonProperty("wrap", NullValueHandling = NullValueHandling.Ignore)]
    public string? Wrap { get; set; }

    /// <summary>
    /// Fixed column count when this component lays its children out as a grid.
    /// </summary>
    [JsonProperty("columns", NullValueHandling = NullValueHandling.Ignore)]
    public int? Columns { get; set; }

    [JsonProperty("overflow", NullValueHandling = NullValueHandling.Ignore)]
    public string? Overflow { get; set; }

}

/// <summary>
/// Appearance, kept apart from geometry so a component can be re-skinned
/// without touching its layout and re-laid-out without touching its skin.
/// Colours are token keys, never hex. A payload carrying hex would render
/// correctly in one theme and wrongly in the other, and would not respond
/// when the user switches.
/// </summary>
public record NmSurface
{
    [JsonProperty("background", NullValueHandling = NullValueHandling.Ignore)]
    public string? Background { get; set; }

    [JsonProperty("foreground", NullValueHandling = NullValueHandling.Ignore)]
    public string? Foreground { get; set; }

    [JsonProperty("border_color", NullValueHandling = NullValueHandling.Ignore)]
    public string? BorderColor { get; set; }

    [JsonProperty("border_width", NullValueHandling = NullValueHandling.Ignore)]
    public string? BorderWidth { get; set; }

    [JsonProperty("radius", NullValueHandling = NullValueHandling.Ignore)]
    public string? Radius { get; set; }

    [JsonProperty("shadow", NullValueHandling = NullValueHandling.Ignore)]
    public string? Shadow { get; set; }

    [JsonProperty("opacity", NullValueHandling = NullValueHandling.Ignore)]
    public int? Opacity { get; set; }

    /// <summary>
    /// How the component lifts when it takes focus. This is the tv surface's
    /// equivalent of hover, which does not exist there.
    /// </summary>
    [JsonProperty("elevation", NullValueHandling = NullValueHandling.Ignore)]
    public string? Elevation { get; set; }

}

/// <summary>
/// Something the client should do when the component is activated. An
/// action names an intent; it never carries code. A client that does not
/// understand an action ignores it rather than guessing, which is what lets
/// a newer server talk to an older client without breaking it.
/// </summary>
public record NmAction
{
    /// <summary>
    /// The intent, such as navigate, play, mutate, dismiss or submit.
    /// </summary>
    [JsonProperty("kind", NullValueHandling = NullValueHandling.Ignore)]
    public string? Kind { get; set; }

    /// <summary>
    /// What the intent applies to, usually a link or a component id.
    /// </summary>
    [JsonProperty("target", NullValueHandling = NullValueHandling.Ignore)]
    public string? Target { get; set; }

    [JsonProperty("body", NullValueHandling = NullValueHandling.Ignore)]
    public object? Body { get; set; }

    /// <summary>
    /// When set, the client confirms with this message before acting.
    /// </summary>
    [JsonProperty("confirm", NullValueHandling = NullValueHandling.Ignore)]
    public string? Confirm { get; set; }

}

/// <summary>
/// The accessible name and role a payload can set. Every component ships a
/// correct default, so this exists to override, not to supply what would
/// otherwise be missing. A component that needs this field filled in to be
/// accessible is a component with a bug.
/// </summary>
public record NmAccessibility
{
    [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
    public string? Label { get; set; }

    [JsonProperty("described_by", NullValueHandling = NullValueHandling.Ignore)]
    public string? DescribedBy { get; set; }

    [JsonProperty("role", NullValueHandling = NullValueHandling.Ignore)]
    public string? Role { get; set; }

    [JsonProperty("live", NullValueHandling = NullValueHandling.Ignore)]
    public string? Live { get; set; }

}

/// <summary>
/// When and from where this component refreshes itself.
/// </summary>
public record NmUpdate
{
    [JsonProperty("when", NullValueHandling = NullValueHandling.Ignore)]
    public string? When { get; set; }

    [JsonProperty("link", NullValueHandling = NullValueHandling.Ignore)]
    public string? Link { get; set; }

    [JsonProperty("body", NullValueHandling = NullValueHandling.Ignore)]
    public object? Body { get; set; }

}

public record NmContextMenuItem
{
    [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
    public string? Id { get; set; }

    [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
    public string? Title { get; set; }

    [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
    public string? Icon { get; set; }

    [JsonProperty("destructive", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Destructive { get; set; }

    [JsonProperty("action", NullValueHandling = NullValueHandling.Ignore)]
    public NmAction? Action { get; set; }

}

/// <summary>
/// The envelope, matching `Component` in `openapi-nm-components.yaml`. The
/// `component` field discriminates, and `props` is that component's own
/// schema, every one of which extends `NMComponentBase`. The concrete
/// component schemas are generated from the design system into
/// `openapi-nm-design-system.components.yaml` and are not hand-written
/// here, because a contract maintained by hand alongside a generated one
/// drifts.
/// </summary>
public record NmComponent
{
    [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
    public string? Id { get; set; }

    /// <summary>
    /// Component type discriminator, such as NMButton or NMCard.
    /// </summary>
    [JsonProperty("component", NullValueHandling = NullValueHandling.Ignore)]
    public string? Component { get; set; }

    /// <summary>
    /// The component's props, extending NMComponentBase.
    /// </summary>
    [JsonProperty("props", NullValueHandling = NullValueHandling.Ignore)]
    public object? Props { get; set; }

    [JsonProperty("update", NullValueHandling = NullValueHandling.Ignore)]
    public NmUpdate? Update { get; set; }

}

/// <summary>
/// What every component in this vocabulary carries, whatever it draws.
/// `items` is here rather than on the container components alone, because a
/// brick that cannot hold children is not a brick. A component that has no
/// meaningful place to put children renders them after its own content.
/// </summary>
public record NmComponentBase
{
    [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
    public string? Id { get; set; }

    /// <summary>
    /// Nested children, rendered inside this component.
    /// </summary>
    [JsonProperty("items")]
    public List<NmComponent> Items { get; set; } = [];

    [JsonProperty("box", NullValueHandling = NullValueHandling.Ignore)]
    public NmBox? Box { get; set; }

    [JsonProperty("surface", NullValueHandling = NullValueHandling.Ignore)]
    public NmSurface? Surface { get; set; }

    /// <summary>
    /// The palette family this component draws its accent from, such as
    /// `violet` or `red`. Any family the design system ships is accepted, not
    /// only the handful a given component enumerates: those are the designer's
    /// recommendation rather than the limit. Absent, the component follows the
    /// accent the app is set to, which is the behaviour a payload should want
    /// almost always. Naming one here is for the case where a single component
    /// has to stand apart from the rest of the interface.
    /// </summary>
    [JsonProperty("color", NullValueHandling = NullValueHandling.Ignore)]
    public string? Color { get; set; }

    [JsonProperty("action", NullValueHandling = NullValueHandling.Ignore)]
    public NmAction? Action { get; set; }

    [JsonProperty("accessibility", NullValueHandling = NullValueHandling.Ignore)]
    public NmAccessibility? Accessibility { get; set; }

    /// <summary>
    /// A stable handle for tests. The box suites read the rendered geometry
    /// through this, which is why it is part of the contract rather than
    /// something each client invents.
    /// </summary>
    [JsonProperty("test_id", NullValueHandling = NullValueHandling.Ignore)]
    public string? TestId { get; set; }

    /// <summary>
    /// The component focus moves to next, for D-pad traversal.
    /// </summary>
    [JsonProperty("next_id", NullValueHandling = NullValueHandling.Ignore)]
    public string? NextId { get; set; }

    [JsonProperty("previous_id", NullValueHandling = NullValueHandling.Ignore)]
    public string? PreviousId { get; set; }

    [JsonProperty("context_menu_items")]
    public List<NmContextMenuItem> ContextMenuItems { get; set; } = [];

    /// <summary>
    /// Where this component's data is fetched or refreshed from.
    /// </summary>
    [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
    public string? Url { get; set; }

    /// <summary>
    /// Anything the contract has not named yet. This is the escape hatch that
    /// keeps an older client alive against a newer server, and it is not a
    /// place to put something that deserves a name.
    /// </summary>
    [JsonProperty("properties", NullValueHandling = NullValueHandling.Ignore)]
    public object? Properties { get; set; }

}
