// -----------------------------------------------------------------------------
//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.
//
//  This file is part of NoMercy MediaServer, source-available software (NOT open
//  source). Personal use and contributions are welcome; distribution, resale,
//  relicensing, and commercial exploitation are prohibited without explicit
//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.
//
//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary
// -----------------------------------------------------------------------------

// Generated by tools/nm-components. Do not edit.

using Newtonsoft.Json;

namespace NoMercy.Design;

/// <summary>
/// Every component name the design system publishes. Reach for these rather
/// than a literal, so a renamed component fails to compile here instead of
/// rendering as nothing on a client.
/// </summary>
public static class NmComponents
{
    public const string Avatar = "NMAvatar";
    public const string Badge = "NMBadge";
    public const string Divider = "NMDivider";
    public const string FormLabel = "NMFormLabel";
    public const string Helper = "NMHelper";
    public const string Image = "NMImage";
    public const string Link = "NMLink";
    public const string Progress = "NMProgress";
    public const string Skeleton = "NMSkeleton";
    public const string Spinner = "NMSpinner";
    public const string Tag = "NMTag";
    public const string Button = "NMButton";
    public const string Checkbox = "NMCheckbox";
    public const string Input = "NMInput";
    public const string Radio = "NMRadio";
    public const string Rating = "NMRating";
    public const string Slider = "NMSlider";
    public const string Textarea = "NMTextarea";
    public const string Toggle = "NMToggle";
    public const string BadgeGroup = "NMBadgeGroup";
    public const string Breadcrumb = "NMBreadcrumb";
    public const string ButtonGroup = "NMButtonGroup";
    public const string CheckboxGroup = "NMCheckboxGroup";
    public const string Pagination = "NMPagination";
    public const string RadioGroup = "NMRadioGroup";
    public const string Segmented = "NMSegmented";
    public const string StepIndicator = "NMStepIndicator";
    public const string Toggles = "NMToggles";
    public const string Alert = "NMAlert";
    public const string Card = "NMCard";
    public const string Chat = "NMChat";
    public const string ContentFooter = "NMContentFooter";
    public const string ContentHeader = "NMContentHeader";
    public const string EmptyState = "NMEmptyState";
    public const string List = "NMList";
    public const string Metrics = "NMMetrics";
    public const string Table = "NMTable";
    public const string ColorPicker = "NMColorPicker";
    public const string Combobox = "NMCombobox";
    public const string CommandPalette = "NMCommandPalette";
    public const string DatePicker = "NMDatePicker";
    public const string Drawer = "NMDrawer";
    public const string Dropdown = "NMDropdown";
    public const string Modal = "NMModal";
    public const string Popover = "NMPopover";
    public const string SearchInput = "NMSearchInput";
    public const string Select = "NMSelect";
    public const string Toast = "NMToast";
    public const string Tooltip = "NMTooltip";
    public const string Accordion = "NMAccordion";
    public const string Carousel = "NMCarousel";
    public const string FileUpload = "NMFileUpload";
    public const string Navigation = "NMNavigation";
    public const string Stepper = "NMStepper";
    public const string Tabs = "NMTabs";
    public const string TreeView = "NMTreeView";
}

/// <summary>
/// What every component carries. Shared rather than repeated on all 56, so a
/// chainable setter can be written once against this and apply everywhere.
/// </summary>
public abstract record NmProps
{
    /// <summary>The name the client dispatches on.</summary>
    [JsonIgnore]
    public abstract string Component { get; }

    [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
    public string? Id { get; set; }

    /// <summary>
    /// Nested children, rendered inside this component.
    /// </summary>
    [JsonProperty("items")]
    public List<NmComponent> Items { get; set; } = [];

    /// <summary>
    /// Children for a slot the component names, keyed by that name. A card
    /// declares a header, a body and a footer; without this a payload could
    /// reach none of them, because every renderer filled the default slot and
    /// nothing else. Anything sent under a name the component does not declare
    /// is ignored rather than drawn somewhere it does not belong.
    /// </summary>
    [JsonProperty("slots", NullValueHandling = NullValueHandling.Ignore)]
    public Dictionary<string, List<NmComponent>>? Slots { get; set; }

    [JsonProperty("box", NullValueHandling = NullValueHandling.Ignore)]
    public NmBox? Box { get; set; }

    [JsonProperty("surface", NullValueHandling = NullValueHandling.Ignore)]
    public NmSurface? Surface { get; set; }

    /// <summary>
    /// The palette family this component draws its accent from, such as
    /// `violet` or `red`. Any family the design system ships is accepted, not
    /// only the handful a given component enumerates: those are the designer's
    /// recommendation rather than the limit. Absent, the component follows the
    /// accent the app is set to, which is the behaviour a payload should want
    /// almost always. Naming one here is for the case where a single component
    /// has to stand apart from the rest of the interface.
    /// </summary>
    [JsonProperty("color", NullValueHandling = NullValueHandling.Ignore)]
    public string? Color { get; set; }

    [JsonProperty("action", NullValueHandling = NullValueHandling.Ignore)]
    public NmAction? Action { get; set; }

    [JsonProperty("accessibility", NullValueHandling = NullValueHandling.Ignore)]
    public NmAccessibility? Accessibility { get; set; }

    /// <summary>
    /// A stable handle for tests. The box suites read the rendered geometry
    /// through this, which is why it is part of the contract rather than
    /// something each client invents.
    /// </summary>
    [JsonProperty("test_id", NullValueHandling = NullValueHandling.Ignore)]
    public string? TestId { get; set; }

    /// <summary>
    /// The component focus moves to next, for D-pad traversal.
    /// </summary>
    [JsonProperty("next_id", NullValueHandling = NullValueHandling.Ignore)]
    public string? NextId { get; set; }

    [JsonProperty("previous_id", NullValueHandling = NullValueHandling.Ignore)]
    public string? PreviousId { get; set; }

    [JsonProperty("context_menu_items")]
    public List<NmContextMenuItem> ContextMenuItems { get; set; } = [];

    /// <summary>
    /// Where this component's data is fetched or refreshed from.
    /// </summary>
    [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
    public string? Url { get; set; }

    /// <summary>
    /// Anything the contract has not named yet. This is the escape hatch that
    /// keeps an older client alive against a newer server, and it is not a
    /// place to put something that deserves a name.
    /// </summary>
    [JsonProperty("properties", NullValueHandling = NullValueHandling.Ignore)]
    public object? Properties { get; set; }

    /// <summary>
    /// Lets a built-up component stand in wherever a component is expected, so
    /// nesting reads as nesting instead of as a conversion call at every level.
    /// </summary>
    public static implicit operator NmComponent(NmProps props) =>
        new()
        {
            Id = props.Id,
            Component = props.Component,
            Props = props,
        };
}

/// <summary>
/// Avatar.
/// </summary>
public record NMAvatarProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Avatar;

    /// <summary>
    /// Alt text for image (required for type="image")
    /// </summary>
    [JsonProperty("alt", NullValueHandling = NullValueHandling.Ignore)]
    public string? Alt { get; set; }

    /// <summary>
    /// ARIA Label
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// The size of the avatar
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Use square shape instead of circular
    /// </summary>
    [JsonProperty("square", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Square { get; set; }

    /// <summary>
    /// Image URL (for type="image")
    /// </summary>
    [JsonProperty("src", NullValueHandling = NullValueHandling.Ignore)]
    public string? Src { get; set; }

    /// <summary>
    /// Status indicator
    /// </summary>
    [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
    public string? Status { get; set; }

    /// <summary>
    /// The type of avatar content
    /// </summary>
    [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
    public string? Type { get; set; }

}

/// <summary>
/// Badge.
/// </summary>
public record NMBadgeProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Badge;

    /// <summary>
    /// Show status dot indicator
    /// </summary>
    [JsonProperty("dot", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Dot { get; set; }

    /// <summary>
    /// Display mode
    /// </summary>
    [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
    public string? Mode { get; set; }

    /// <summary>
    /// Badge size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Badge text content
    /// </summary>
    [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
    public string? Text { get; set; }

    /// <summary>
    /// Visual style variant
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Divider.
/// </summary>
public record NMDividerProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Divider;

    /// <summary>
    /// Text label content
    /// </summary>
    [JsonProperty("labelText", NullValueHandling = NullValueHandling.Ignore)]
    public string? LabelText { get; set; }

    /// <summary>
    /// Line style
    /// </summary>
    [JsonProperty("line", NullValueHandling = NullValueHandling.Ignore)]
    public string? Line { get; set; }

    /// <summary>
    /// Content placement
    /// </summary>
    [JsonProperty("placement", NullValueHandling = NullValueHandling.Ignore)]
    public string? Placement { get; set; }

}

/// <summary>
/// Label.
/// </summary>
public record NMFormLabelProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.FormLabel;

    /// <summary>
    /// Disabled state
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Show info icon
    /// </summary>
    [JsonProperty("infoIcon", NullValueHandling = NullValueHandling.Ignore)]
    public bool? InfoIcon { get; set; }

    /// <summary>
    /// Info icon tooltip
    /// </summary>
    [JsonProperty("infoTooltip", NullValueHandling = NullValueHandling.Ignore)]
    public string? InfoTooltip { get; set; }

    /// <summary>
    /// Label text
    /// </summary>
    [JsonProperty("labelText", NullValueHandling = NullValueHandling.Ignore)]
    public string? LabelText { get; set; }

    /// <summary>
    /// Label marker type
    /// </summary>
    [JsonProperty("marker", NullValueHandling = NullValueHandling.Ignore)]
    public string? Marker { get; set; }

    /// <summary>
    /// Custom marker text
    /// </summary>
    [JsonProperty("markerText", NullValueHandling = NullValueHandling.Ignore)]
    public string? MarkerText { get; set; }

}

/// <summary>
/// Helper.
/// </summary>
public record NMHelperProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Helper;

    /// <summary>
    /// Helper text content
    /// </summary>
    [JsonProperty("helperText", NullValueHandling = NullValueHandling.Ignore)]
    public string? HelperText { get; set; }

    /// <summary>
    /// Show icon
    /// </summary>
    [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Icon { get; set; }

    /// <summary>
    /// Icon tooltip text
    /// </summary>
    [JsonProperty("iconTooltip", NullValueHandling = NullValueHandling.Ignore)]
    public string? IconTooltip { get; set; }

    /// <summary>
    /// Helper status
    /// </summary>
    [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
    public string? Status { get; set; }

}

/// <summary>
/// Image.
/// </summary>
public record NMImageProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Image;

    /// <summary>
    /// Alt text for accessibility
    /// </summary>
    [JsonProperty("alt", NullValueHandling = NullValueHandling.Ignore)]
    public string? Alt { get; set; }

    /// <summary>
    /// Image aspect ratio
    /// </summary>
    [JsonProperty("aspectRatio", NullValueHandling = NullValueHandling.Ignore)]
    public string? AspectRatio { get; set; }

    /// <summary>
    /// Show border
    /// </summary>
    [JsonProperty("border", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Border { get; set; }

    /// <summary>
    /// Enable hover zoom effect
    /// </summary>
    [JsonProperty("clickable", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Clickable { get; set; }

    /// <summary>
    /// Object fit behavior
    /// </summary>
    [JsonProperty("fit", NullValueHandling = NullValueHandling.Ignore)]
    public string? Fit { get; set; }

    /// <summary>
    /// Border radius
    /// </summary>
    [JsonProperty("rounded", NullValueHandling = NullValueHandling.Ignore)]
    public string? Rounded { get; set; }

    /// <summary>
    /// Shadow elevation
    /// </summary>
    [JsonProperty("shadow", NullValueHandling = NullValueHandling.Ignore)]
    public string? Shadow { get; set; }

    /// <summary>
    /// Image source URL
    /// </summary>
    [JsonProperty("src", NullValueHandling = NullValueHandling.Ignore)]
    public string? Src { get; set; }

}

/// <summary>
/// Link.
/// </summary>
public record NMLinkProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Link;

    /// <summary>
    /// Disable link interaction
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Open in new tab
    /// </summary>
    [JsonProperty("external", NullValueHandling = NullValueHandling.Ignore)]
    public bool? External { get; set; }

    /// <summary>
    /// Show icon
    /// </summary>
    [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Icon { get; set; }

    /// <summary>
    /// Icon position
    /// </summary>
    [JsonProperty("iconPosition", NullValueHandling = NullValueHandling.Ignore)]
    public string? IconPosition { get; set; }

    /// <summary>
    /// Link size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Link text content
    /// </summary>
    [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
    public string? Text { get; set; }

    /// <summary>
    /// Link visual style
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Progress.
/// </summary>
public record NMProgressProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Progress;

    /// <summary>
    /// Accessible label
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Label position
    /// </summary>
    [JsonProperty("labelPos", NullValueHandling = NullValueHandling.Ignore)]
    public string? LabelPos { get; set; }

    /// <summary>
    /// Track height
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Progress value (0-100)
    /// </summary>
    [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
    public int? Value { get; set; }

}

/// <summary>
/// Skeleton.
/// </summary>
public record NMSkeletonProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Skeleton;

    /// <summary>
    /// Skeleton shape
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Spinner.
/// </summary>
public record NMSpinnerProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Spinner;

    /// <summary>
    /// Accessible label
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Spinner size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Tag.
/// </summary>
public record NMTagProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Tag;

    /// <summary>
    /// Show leading avatar
    /// </summary>
    [JsonProperty("avatar", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Avatar { get; set; }

    /// <summary>
    /// Show leading checkbox
    /// </summary>
    [JsonProperty("checkbox", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Checkbox { get; set; }

    /// <summary>
    /// Show count pill
    /// </summary>
    [JsonProperty("count", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Count { get; set; }

    /// <summary>
    /// Count value
    /// </summary>
    [JsonProperty("countText", NullValueHandling = NullValueHandling.Ignore)]
    public string? CountText { get; set; }

    /// <summary>
    /// Show leading icon
    /// </summary>
    [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Icon { get; set; }

    /// <summary>
    /// Tag size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Tag label text
    /// </summary>
    [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
    public string? Text { get; set; }

    /// <summary>
    /// Show close button
    /// </summary>
    [JsonProperty("xclose", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Xclose { get; set; }

}

/// <summary>
/// Button.
/// </summary>
public record NMButtonProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Button;

    /// <summary>
    /// Accessible label for icon-only buttons
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Whether the button is disabled
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Whether to render as icon-only (hides label)
    /// </summary>
    [JsonProperty("iconOnly", NullValueHandling = NullValueHandling.Ignore)]
    public bool? IconOnly { get; set; }

    /// <summary>
    /// Whether the button is in a loading state
    /// </summary>
    [JsonProperty("loading", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Loading { get; set; }

    /// <summary>
    /// The size of the button
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// The visual style variant of the button
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Checkbox.
/// </summary>
public record NMCheckboxProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Checkbox;

    /// <summary>
    /// Accessible name, used when there is no labelText
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Whether the checkbox is checked or indeterminate
    /// </summary>
    [JsonProperty("checked", NullValueHandling = NullValueHandling.Ignore)]
    public string? Checked { get; set; }

    /// <summary>
    /// Whether the checkbox is disabled
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Optional helper text below label
    /// </summary>
    [JsonProperty("helperText", NullValueHandling = NullValueHandling.Ignore)]
    public string? HelperText { get; set; }

    /// <summary>
    /// Optional label text
    /// </summary>
    [JsonProperty("labelText", NullValueHandling = NullValueHandling.Ignore)]
    public string? LabelText { get; set; }

    /// <summary>
    /// The size of the checkbox
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Input.
/// </summary>
public record NMInputProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Input;

    /// <summary>
    /// Whether the input is disabled
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Whether the input has a validation error
    /// </summary>
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Error { get; set; }

    /// <summary>
    /// Leading text value
    /// </summary>
    [JsonProperty("leadingTextValue", NullValueHandling = NullValueHandling.Ignore)]
    public string? LeadingTextValue { get; set; }

    /// <summary>
    /// Placeholder text shown when empty
    /// </summary>
    [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
    public string? Placeholder { get; set; }

    /// <summary>
    /// The size of the input field
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Radio.
/// </summary>
public record NMRadioProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Radio;

    /// <summary>
    /// Accessible name, used when there is no labelText
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Whether the radio is selected
    /// </summary>
    [JsonProperty("checked", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Checked { get; set; }

    /// <summary>
    /// Whether the radio is disabled
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Optional helper text below label
    /// </summary>
    [JsonProperty("helperText", NullValueHandling = NullValueHandling.Ignore)]
    public string? HelperText { get; set; }

    /// <summary>
    /// Optional label text
    /// </summary>
    [JsonProperty("labelText", NullValueHandling = NullValueHandling.Ignore)]
    public string? LabelText { get; set; }

    /// <summary>
    /// Group name for mutual exclusivity
    /// </summary>
    [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
    public string? Name { get; set; }

    /// <summary>
    /// The size of the radio button
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Value submitted with form
    /// </summary>
    [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
    public string? Value { get; set; }

}

/// <summary>
/// Rating.
/// </summary>
public record NMRatingProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Rating;

    /// <summary>
    /// Review count shown in parentheses next to label
    /// </summary>
    [JsonProperty("count", NullValueHandling = NullValueHandling.Ignore)]
    public int? Count { get; set; }

    /// <summary>
    /// Disable interaction
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Maximum rating (number of stars)
    /// </summary>
    [JsonProperty("max", NullValueHandling = NullValueHandling.Ignore)]
    public string? Max { get; set; }

    /// <summary>
    /// Read-only display or interactive input
    /// </summary>
    [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
    public string? Mode { get; set; }

    /// <summary>
    /// Show numeric value label
    /// </summary>
    [JsonProperty("showLabel", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowLabel { get; set; }

    /// <summary>
    /// Star icon size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Current rating value (supports 0.5 increments)
    /// </summary>
    [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
    public string? Value { get; set; }

}

/// <summary>
/// Sliders &amp; Ranges.
/// </summary>
public record NMSliderProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Slider;

    /// <summary>
    /// Accessible label
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Disable slider interaction
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Enable range mode with two thumbs
    /// </summary>
    [JsonProperty("isBiValue", NullValueHandling = NullValueHandling.Ignore)]
    public bool? IsBiValue { get; set; }

    /// <summary>
    /// Label display mode
    /// </summary>
    [JsonProperty("labelMode", NullValueHandling = NullValueHandling.Ignore)]
    public string? LabelMode { get; set; }

    /// <summary>
    /// Track height
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Current value (0-100)
    /// </summary>
    [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
    public int? Value { get; set; }

    /// <summary>
    /// Second value for range mode
    /// </summary>
    [JsonProperty("value2", NullValueHandling = NullValueHandling.Ignore)]
    public int? Value2 { get; set; }

}

/// <summary>
/// Textarea.
/// </summary>
public record NMTextareaProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Textarea;

    /// <summary>
    /// Whether the textarea is disabled
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Whether the textarea has a validation error
    /// </summary>
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Error { get; set; }

    /// <summary>
    /// Maximum character limit
    /// </summary>
    [JsonProperty("maxChars", NullValueHandling = NullValueHandling.Ignore)]
    public int? MaxChars { get; set; }

    /// <summary>
    /// Placeholder text shown when empty
    /// </summary>
    [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
    public string? Placeholder { get; set; }

    /// <summary>
    /// Resize behavior
    /// </summary>
    [JsonProperty("resize", NullValueHandling = NullValueHandling.Ignore)]
    public string? Resize { get; set; }

    /// <summary>
    /// Show character counter
    /// </summary>
    [JsonProperty("showCounter", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowCounter { get; set; }

    /// <summary>
    /// The size of the textarea
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Switch.
/// </summary>
public record NMToggleProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Toggle;

    /// <summary>
    /// Accessible name, used when there is no labelText
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Whether the switch is on
    /// </summary>
    [JsonProperty("checked", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Checked { get; set; }

    /// <summary>
    /// Whether the switch is disabled
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Optional helper text below label
    /// </summary>
    [JsonProperty("helperText", NullValueHandling = NullValueHandling.Ignore)]
    public string? HelperText { get; set; }

    /// <summary>
    /// Optional label text
    /// </summary>
    [JsonProperty("labelText", NullValueHandling = NullValueHandling.Ignore)]
    public string? LabelText { get; set; }

    /// <summary>
    /// The size of the switch
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Badge Group.
/// </summary>
public record NMBadgeGroupProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.BadgeGroup;

    /// <summary>
    /// Badge position relative to text
    /// </summary>
    [JsonProperty("badgePos", NullValueHandling = NullValueHandling.Ignore)]
    public string? BadgePos { get; set; }

    /// <summary>
    /// Badge group size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Badge visual style
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Breadcrumb.
/// </summary>
public record NMBreadcrumbProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Breadcrumb;

    /// <summary>
    /// Array of breadcrumb labels
    /// </summary>
    [JsonProperty("labels", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<string>? Labels { get; set; }

    /// <summary>
    /// Separator style
    /// </summary>
    [JsonProperty("separator", NullValueHandling = NullValueHandling.Ignore)]
    public string? Separator { get; set; }

}

/// <summary>
/// Button Group.
/// </summary>
public record NMButtonGroupProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.ButtonGroup;

}

/// <summary>
/// Checkbox Group.
/// </summary>
public record NMCheckboxGroupProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.CheckboxGroup;

    /// <summary>
    /// Disabled state for the group
    /// </summary>
    [JsonProperty("groupDisabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? GroupDisabled { get; set; }

    /// <summary>
    /// Error state for the group
    /// </summary>
    [JsonProperty("groupError", NullValueHandling = NullValueHandling.Ignore)]
    public bool? GroupError { get; set; }

    /// <summary>
    /// Layout direction
    /// </summary>
    [JsonProperty("layout", NullValueHandling = NullValueHandling.Ignore)]
    public string? Layout { get; set; }

    /// <summary>
    /// Checkbox group size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Pagination.
/// </summary>
public record NMPaginationProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Pagination;

    /// <summary>
    /// Current page number
    /// </summary>
    [JsonProperty("currentPage", NullValueHandling = NullValueHandling.Ignore)]
    public int? CurrentPage { get; set; }

    /// <summary>
    /// Pagination size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Total number of pages
    /// </summary>
    [JsonProperty("totalPages", NullValueHandling = NullValueHandling.Ignore)]
    public int? TotalPages { get; set; }

}

/// <summary>
/// Radio Group.
/// </summary>
public record NMRadioGroupProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.RadioGroup;

    /// <summary>
    /// Disabled state for the group
    /// </summary>
    [JsonProperty("groupDisabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? GroupDisabled { get; set; }

    /// <summary>
    /// Error state for the group
    /// </summary>
    [JsonProperty("groupError", NullValueHandling = NullValueHandling.Ignore)]
    public bool? GroupError { get; set; }

    /// <summary>
    /// Layout direction
    /// </summary>
    [JsonProperty("layout", NullValueHandling = NullValueHandling.Ignore)]
    public string? Layout { get; set; }

    /// <summary>
    /// Radio group size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Segmented.
/// </summary>
public record NMSegmentedProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Segmented;

    /// <summary>
    /// Disable all segments
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Expand to full container width
    /// </summary>
    [JsonProperty("fullWidth", NullValueHandling = NullValueHandling.Ignore)]
    public bool? FullWidth { get; set; }

    /// <summary>
    /// Segmented control size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Currently selected value
    /// </summary>
    [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
    public string? Value { get; set; }

}

/// <summary>
/// Step Indicator.
/// </summary>
public record NMStepIndicatorProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.StepIndicator;

    /// <summary>
    /// Zero-based index of current step
    /// </summary>
    [JsonProperty("activeIndex", NullValueHandling = NullValueHandling.Ignore)]
    public string? ActiveIndex { get; set; }

    /// <summary>
    /// Indicator size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Total number of steps
    /// </summary>
    [JsonProperty("steps", NullValueHandling = NullValueHandling.Ignore)]
    public string? Steps { get; set; }

    /// <summary>
    /// Visual variant
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Toggles.
/// </summary>
public record NMTogglesProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Toggles;

    /// <summary>
    /// Disabled state
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Toggle size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Toggle state
    /// </summary>
    [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
    public string? State { get; set; }

    /// <summary>
    /// Toggle type
    /// </summary>
    [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
    public string? Type { get; set; }

}

/// <summary>
/// Notification.
/// </summary>
public record NMAlertProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Alert;

    /// <summary>
    /// Show close button
    /// </summary>
    [JsonProperty("closable", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Closable { get; set; }

    /// <summary>
    /// Enable glow effect (accent style only)
    /// </summary>
    [JsonProperty("glow", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Glow { get; set; }

    /// <summary>
    /// Semantic severity level
    /// </summary>
    [JsonProperty("severity", NullValueHandling = NullValueHandling.Ignore)]
    public string? Severity { get; set; }

    /// <summary>
    /// Alert size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Visual style
    /// </summary>
    [JsonProperty("style", NullValueHandling = NullValueHandling.Ignore)]
    public string? Style { get; set; }

}

/// <summary>
/// Card.
/// </summary>
public record NMCardProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Card;

    /// <summary>
    /// Footer variant
    /// </summary>
    [JsonProperty("footerVariant", NullValueHandling = NullValueHandling.Ignore)]
    public string? FooterVariant { get; set; }

    /// <summary>
    /// Internal padding size
    /// </summary>
    [JsonProperty("padding", NullValueHandling = NullValueHandling.Ignore)]
    public string? Padding { get; set; }

    /// <summary>
    /// Card visual style
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Chat.
/// </summary>
public record NMChatProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Chat;

    /// <summary>
    /// Array of message objects
    /// </summary>
    [JsonProperty("messages", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<NmChatMessage>? Messages { get; set; }

}

/// <summary>
/// ContentFooter.
/// </summary>
public record NMContentFooterProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.ContentFooter;

    /// <summary>
    /// Footer variant
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// ContentHeader.
/// </summary>
public record NMContentHeaderProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.ContentHeader;

    /// <summary>
    /// Show close button
    /// </summary>
    [JsonProperty("canClose", NullValueHandling = NullValueHandling.Ignore)]
    public bool? CanClose { get; set; }

    /// <summary>
    /// id put on the title, for a dialog to reference with aria-labelledby
    /// </summary>
    [JsonProperty("titleId", NullValueHandling = NullValueHandling.Ignore)]
    public string? TitleId { get; set; }

}

/// <summary>
/// Empty States.
/// </summary>
public record NMEmptyStateProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.EmptyState;

    /// <summary>
    /// Empty state layout variant
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// List.
/// </summary>
public record NMListProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.List;

    /// <summary>
    /// Bullet style for unordered lists
    /// </summary>
    [JsonProperty("bullet", NullValueHandling = NullValueHandling.Ignore)]
    public string? Bullet { get; set; }

    /// <summary>
    /// Horizontal layout
    /// </summary>
    [JsonProperty("horizontal", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Horizontal { get; set; }

    /// <summary>
    /// Numbering style for ordered lists
    /// </summary>
    [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
    public string? Order { get; set; }

    /// <summary>
    /// List size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// List type
    /// </summary>
    [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
    public string? Type { get; set; }

}

/// <summary>
/// Metrics.
/// </summary>
public record NMMetricsProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Metrics;

    /// <summary>
    /// Change indicator
    /// </summary>
    [JsonProperty("change", NullValueHandling = NullValueHandling.Ignore)]
    public string? Change { get; set; }

    /// <summary>
    /// Metric label
    /// </summary>
    [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
    public string? Label { get; set; }

    /// <summary>
    /// Show decorative icon
    /// </summary>
    [JsonProperty("showIcon", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowIcon { get; set; }

    /// <summary>
    /// Trend direction
    /// </summary>
    [JsonProperty("trend", NullValueHandling = NullValueHandling.Ignore)]
    public string? Trend { get; set; }

    /// <summary>
    /// Metric value
    /// </summary>
    [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
    public string? Value { get; set; }

    /// <summary>
    /// Metric visual style
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Table.
/// </summary>
public record NMTableProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Table;

    /// <summary>
    /// Array of column definitions
    /// </summary>
    [JsonProperty("columns", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<NmTableColumn>? Columns { get; set; }

    /// <summary>
    /// Row hover effect
    /// </summary>
    [JsonProperty("hover", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Hover { get; set; }

    /// <summary>
    /// Array of row data
    /// </summary>
    [JsonProperty("rows", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<NmTableRow>? Rows { get; set; }

    /// <summary>
    /// Table size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Alternate row background colors
    /// </summary>
    [JsonProperty("striped", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Striped { get; set; }

    /// <summary>
    /// Table visual style
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Color Picker.
/// </summary>
public record NMColorPickerProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.ColorPicker;

    /// <summary>
    /// Disable the swatch trigger
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Optional label text above the swatch
    /// </summary>
    [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
    public string? Label { get; set; }

    /// <summary>
    /// Current hex colour value
    /// </summary>
    [JsonProperty("selected", NullValueHandling = NullValueHandling.Ignore)]
    public string? Selected { get; set; }

    /// <summary>
    /// Show hex input row in panel
    /// </summary>
    [JsonProperty("showInput", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowInput { get; set; }

    /// <summary>
    /// Show the colour picker panel
    /// </summary>
    [JsonProperty("showPanel", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowPanel { get; set; }

    /// <summary>
    /// Trigger and palette option size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Combobox.
/// </summary>
public record NMComboboxProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Combobox;

    /// <summary>
    /// Current filter / typed text
    /// </summary>
    [JsonProperty("filterText", NullValueHandling = NullValueHandling.Ignore)]
    public string? FilterText { get; set; }

    /// <summary>
    /// Show spinner instead of chevron
    /// </summary>
    [JsonProperty("isLoading", NullValueHandling = NullValueHandling.Ignore)]
    public bool? IsLoading { get; set; }

    /// <summary>
    /// Enable multi-select tag mode
    /// </summary>
    [JsonProperty("multiple", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Multiple { get; set; }

    /// <summary>
    /// Input placeholder text
    /// </summary>
    [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
    public string? Placeholder { get; set; }

    /// <summary>
    /// Currently selected option (single-select mode)
    /// </summary>
    [JsonProperty("selected", NullValueHandling = NullValueHandling.Ignore)]
    public string? Selected { get; set; }

    /// <summary>
    /// Currently selected options (multi-select mode)
    /// </summary>
    [JsonProperty("selectedItems", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<string>? SelectedItems { get; set; }

    /// <summary>
    /// Field and option item size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Ctrl + K.
/// </summary>
public record NMCommandPaletteProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.CommandPalette;

    /// <summary>
    /// Search input value
    /// </summary>
    [JsonProperty("searchText", NullValueHandling = NullValueHandling.Ignore)]
    public string? SearchText { get; set; }

}

/// <summary>
/// Date Picker.
/// </summary>
public record NMDatePickerProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.DatePicker;

    /// <summary>
    /// Date picker mode
    /// </summary>
    [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
    public string? Mode { get; set; }

    /// <summary>
    /// Calendar size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Drawer.
/// </summary>
public record NMDrawerProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Drawer;

    /// <summary>
    /// Show backdrop overlay
    /// </summary>
    [JsonProperty("hasOverlay", NullValueHandling = NullValueHandling.Ignore)]
    public bool? HasOverlay { get; set; }

    /// <summary>
    /// Open
    /// </summary>
    [JsonProperty("isOpen", NullValueHandling = NullValueHandling.Ignore)]
    public bool? IsOpen { get; set; }

    /// <summary>
    /// Edge to anchor the drawer
    /// </summary>
    [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
    public string? Position { get; set; }

    /// <summary>
    /// Drawer width (left/right) or height (top/bottom)
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Dropdown.
/// </summary>
public record NMDropdownProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Dropdown;

    /// <summary>
    /// Dropdown size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Modal.
/// </summary>
public record NMModalProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Modal;

    /// <summary>
    /// Footer variant
    /// </summary>
    [JsonProperty("footerVariant", NullValueHandling = NullValueHandling.Ignore)]
    public string? FooterVariant { get; set; }

    /// <summary>
    /// Modal width
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Popover.
/// </summary>
public record NMPopoverProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Popover;

    /// <summary>
    /// Open
    /// </summary>
    [JsonProperty("isOpen", NullValueHandling = NullValueHandling.Ignore)]
    public bool? IsOpen { get; set; }

    /// <summary>
    /// Popover position relative to trigger
    /// </summary>
    [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
    public string? Position { get; set; }

    /// <summary>
    /// Show arrow pointing to trigger
    /// </summary>
    [JsonProperty("showArrow", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowArrow { get; set; }

    /// <summary>
    /// Show close button
    /// </summary>
    [JsonProperty("showClose", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowClose { get; set; }

    /// <summary>
    /// Popover panel width
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Search Input.
/// </summary>
public record NMSearchInputProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.SearchInput;

    /// <summary>
    /// Placeholder text
    /// </summary>
    [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
    public string? Placeholder { get; set; }

    /// <summary>
    /// Field height and font size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Current input value — shows clear button when non-empty
    /// </summary>
    [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
    public string? Value { get; set; }

}

/// <summary>
/// Select.
/// </summary>
public record NMSelectProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Select;

    /// <summary>
    /// Whether the select is disabled
    /// </summary>
    [JsonProperty("disabled", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Disabled { get; set; }

    /// <summary>
    /// Whether the select has a validation error
    /// </summary>
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Error { get; set; }

    /// <summary>
    /// Array of selectable options
    /// </summary>
    [JsonProperty("options", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<NmSelectOption>? Options { get; set; }

    /// <summary>
    /// Placeholder text shown when no option is selected
    /// </summary>
    [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
    public string? Placeholder { get; set; }

    /// <summary>
    /// The size of the select field
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}

/// <summary>
/// Toast.
/// </summary>
public record NMToastProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Toast;

    /// <summary>
    /// Show close button
    /// </summary>
    [JsonProperty("closable", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Closable { get; set; }

    /// <summary>
    /// Auto-dismiss duration (ms)
    /// </summary>
    [JsonProperty("duration", NullValueHandling = NullValueHandling.Ignore)]
    public int? Duration { get; set; }

    /// <summary>
    /// Toast message
    /// </summary>
    [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
    public string? Message { get; set; }

    /// <summary>
    /// Screen position
    /// </summary>
    [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
    public string? Position { get; set; }

    /// <summary>
    /// Show action button
    /// </summary>
    [JsonProperty("showAction", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowAction { get; set; }

    /// <summary>
    /// Show variant icon
    /// </summary>
    [JsonProperty("showIcon", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowIcon { get; set; }

    /// <summary>
    /// Show progress bar
    /// </summary>
    [JsonProperty("showProgress", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowProgress { get; set; }

    /// <summary>
    /// Toast title
    /// </summary>
    [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
    public string? Title { get; set; }

    /// <summary>
    /// Toast variant
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Tooltip.
/// </summary>
public record NMTooltipProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Tooltip;

    /// <summary>
    /// Tooltip position relative to trigger
    /// </summary>
    [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
    public string? Position { get; set; }

}

/// <summary>
/// Accordion.
/// </summary>
public record NMAccordionProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Accordion;

    /// <summary>
    /// Allow Multiple Open
    /// </summary>
    [JsonProperty("allowMultiple", NullValueHandling = NullValueHandling.Ignore)]
    public bool? AllowMultiple { get; set; }

    /// <summary>
    /// Array of content for each item
    /// </summary>
    [JsonProperty("content", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<string>? Content { get; set; }

    /// <summary>
    /// Object mapping item indices to disabled state
    /// </summary>
    [JsonProperty("disabledItems", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyDictionary<string, bool>? DisabledItems { get; set; }

    /// <summary>
    /// Object mapping item indices to open state
    /// </summary>
    [JsonProperty("openItems", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyDictionary<string, bool>? OpenItems { get; set; }

    /// <summary>
    /// Show chevron indicator
    /// </summary>
    [JsonProperty("showChevron", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowChevron { get; set; }

    /// <summary>
    /// Accordion size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Accordion visual style
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Carousel.
/// </summary>
public record NMCarouselProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Carousel;

    /// <summary>
    /// Position nav arrows outside viewport
    /// </summary>
    [JsonProperty("navOutside", NullValueHandling = NullValueHandling.Ignore)]
    public bool? NavOutside { get; set; }

    /// <summary>
    /// Show dot pagination
    /// </summary>
    [JsonProperty("showDots", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowDots { get; set; }

    /// <summary>
    /// Show navigation arrows
    /// </summary>
    [JsonProperty("showNav", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowNav { get; set; }

    /// <summary>
    /// Carousel size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Enable scroll snap
    /// </summary>
    [JsonProperty("snap", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Snap { get; set; }

}

/// <summary>
/// File Upload.
/// </summary>
public record NMFileUploadProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.FileUpload;

    /// <summary>
    /// File metadata
    /// </summary>
    [JsonProperty("fileMeta", NullValueHandling = NullValueHandling.Ignore)]
    public string? FileMeta { get; set; }

    /// <summary>
    /// File name
    /// </summary>
    [JsonProperty("fileName", NullValueHandling = NullValueHandling.Ignore)]
    public string? FileName { get; set; }

    /// <summary>
    /// Upload progress percentage
    /// </summary>
    [JsonProperty("uploadPct", NullValueHandling = NullValueHandling.Ignore)]
    public int? UploadPct { get; set; }

}

/// <summary>
/// Navigation.
/// </summary>
public record NMNavigationProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Navigation;

    /// <summary>
    /// Currently active item index
    /// </summary>
    [JsonProperty("activeIndex", NullValueHandling = NullValueHandling.Ignore)]
    public string? ActiveIndex { get; set; }

    /// <summary>
    /// Navigation layout style
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Stepper.
/// </summary>
public record NMStepperProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Stepper;

    /// <summary>
    /// Zero-based index of the current active step
    /// </summary>
    [JsonProperty("activeIndex", NullValueHandling = NullValueHandling.Ignore)]
    public string? ActiveIndex { get; set; }

    /// <summary>
    /// Layout direction
    /// </summary>
    [JsonProperty("orientation", NullValueHandling = NullValueHandling.Ignore)]
    public string? Orientation { get; set; }

    /// <summary>
    /// Circle and text size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Array of step objects with label and optional description
    /// </summary>
    [JsonProperty("steps", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<NmStep>? Steps { get; set; }

}

/// <summary>
/// Tabs.
/// </summary>
public record NMTabsProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.Tabs;

    /// <summary>
    /// Currently active tab index
    /// </summary>
    [JsonProperty("activeIndex", NullValueHandling = NullValueHandling.Ignore)]
    public string? ActiveIndex { get; set; }

    /// <summary>
    /// Accessible name for the tablist
    /// </summary>
    [JsonProperty("ariaLabel", NullValueHandling = NullValueHandling.Ignore)]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Tab size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

    /// <summary>
    /// Array of tab labels
    /// </summary>
    [JsonProperty("tabLabels", NullValueHandling = NullValueHandling.Ignore)]
    public IReadOnlyList<string>? TabLabels { get; set; }

    /// <summary>
    /// Base id for the tabs. Pass one and each tab gets
    /// aria-controls="{tablistId}-panel-{index}", which is the id your panel
    /// needs
    /// </summary>
    [JsonProperty("tablistId", NullValueHandling = NullValueHandling.Ignore)]
    public string? TablistId { get; set; }

    /// <summary>
    /// Tab visual style
    /// </summary>
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    public string? Variant { get; set; }

}

/// <summary>
/// Tree View.
/// </summary>
public record NMTreeViewProps : NmProps
{
    /// <inheritdoc />
    public override string Component => NmComponents.TreeView;

    /// <summary>
    /// Show vertical indent guide lines
    /// </summary>
    [JsonProperty("showLines", NullValueHandling = NullValueHandling.Ignore)]
    public bool? ShowLines { get; set; }

    /// <summary>
    /// Row spacing and icon size
    /// </summary>
    [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
    public string? Size { get; set; }

}
