<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/MovieAppendsResponse.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NoMercy.Providers\NoMercy.Providers.csproj" />
  </ItemGroup>

</Project>
