// -----------------------------------------------------------------------------
//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.
//
//  This file is part of NoMercy MediaServer, source-available software (NOT open
//  source). Personal use and contributions are welcome; distribution, resale,
//  relicensing, and commercial exploitation are prohibited without explicit
//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.
//
//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary
// -----------------------------------------------------------------------------

using System.Net;
using System.Net.Sockets;
using Amazon.Runtime;
using Amazon.S3;
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Containers;
using DotNet.Testcontainers.Images;
using NoMercy.Storage.Drivers.Nfs;
using NoMercy.Storage.Drivers.S3;
using NoMercy.Storage.Drivers.Smb;
using NoMercy.Storage.Drivers.WebDav;
using WebDav;

namespace NoMercy.Tests.Storage.Container;

/// <summary>
/// One all-in-one container for the whole storage test assembly: real MinIO
/// (S3 :9000), Apache mod_dav (WebDAV :8080) and the Linux kernel nfsd (NFSv4
/// :2049) over a shared /data root. Built once from the Dockerfile next to this
/// file, started once, seeded once, and disposed after the last storage test.
///
/// It runs with host networking + --privileged: Docker Desktop's NAT proxy
/// mangles the NFSv4 mount RPC, and the kernel nfsd needs privileged mode and a
/// real ext4 export (a named volume — overlayfs can't be NFS-exported). Those
/// constraints are why this is one shared container, not per-driver fixtures.
///
/// Any startup failure is captured in <see cref="StartupError"/> and surfaced
/// in the test skip message instead of being swallowed into a silent skip.
/// </summary>
public sealed class StorageBackendsFixture : IAsyncLifetime
{
    private IFutureDockerImage? _image;
    private IContainer? _container;

    public bool Available { get; private set; }
    public string? StartupError { get; private set; }

    // ── S3 (MinIO) ───────────────────────────────────────────────────────────
    public const string S3AccessKey = "minioadmin";
    public const string S3SecretKey = "minioadmin";
    public const string S3Bucket = "nomercy-test";
    public string S3Endpoint { get; private set; } = string.Empty;

    // ── WebDAV (Apache mod_dav) ──────────────────────────────────────────────
    public const string WebDavUser = "testuser";
    public const string WebDavPassword = "testpass";
    public string WebDavBaseUrl { get; private set; } = string.Empty;

    // ── SMB (Samba) ──────────────────────────────────────────────────────────
    public const string SmbHost = "127.0.0.1";

    // Samba listens on 1445, not 445: on Windows the OS SMB server owns
    // 127.0.0.1:445, so a host-network container's Samba must use a free port.
    public const int SmbPort = 1445;
    public const string SmbShare = "share";
    public const string SmbUser = "testuser";
    public const string SmbPassword = "testpass";

    // ── NFS (kernel nfsd) ────────────────────────────────────────────────────
    // libnfs resolves the host itself and rejects "localhost" on Windows
    // ("Can not resolv into IPv4/v6 structure") — give it a literal IPv4 loopback.
    // fsid=0 in /etc/exports makes /data/nfs the NFSv4 pseudo-root, so the client
    // mounts "/" and sees the export contents directly.
    public const string NfsHost = "127.0.0.1";
    public const string NfsExport = "/";

    /// <summary>
    /// True once a libnfs mount of the export has actually succeeded. False when
    /// libnfs isn't installed or the export never became mountable — NFS tests
    /// skip with that distinction instead of failing.
    /// </summary>
    public bool NfsMountable { get; private set; }
    public string? NfsUnavailableReason { get; private set; }

    // ── Encoder media generated by the container's ffmpeg ────────────────────
    // Host directory the container writes synthetic clips into (bind-mounted).
    public string MediaDir { get; private set; } = string.Empty;

    // Named volume backing the NFS export (real ext4 — see the mount comment).
    private string _nfsVolumeName = string.Empty;
    private string NfsVolumeName => _nfsVolumeName;

    public async Task InitializeAsync()
    {
        if (!await DockerEnvironment.IsAvailableAsync())
        {
            StartupError = "Docker is not available (docker info failed).";
            Available = false;
            return;
        }

        try
        {
            // The Dockerfile + configs ship next to the test sources; locate them
            // relative to the repo so an out-of-tree bin/ still finds them.
            string dockerfileDir = LocateContainerDir();

            MediaDir = Path.Combine(
                Path.GetTempPath(),
                "nm-storage-media-" + Guid.NewGuid().ToString("N")[..8]
            );
            Directory.CreateDirectory(MediaDir);

            _nfsVolumeName = "nm-nfs-" + Guid.NewGuid().ToString("N")[..8];

            _image = new ImageFromDockerfileBuilder()
                .WithDockerfileDirectory(dockerfileDir)
                .WithDockerfile("Dockerfile")
                .WithName("nomercy-storage-backends:test")
                .WithCleanUp(false) // reuse the cached image across runs
                .Build();
            await _image.CreateAsync();

            _container = new ContainerBuilder()
                .WithImage(_image)
                // Host networking: the container binds the host's network
                // namespace directly, so S3/WebDAV/NFS are reachable at their
                // real ports with no per-port NAT forwarding. The NAT proxy
                // mangles the NFSv4 mount RPC; host networking avoids it. Docker
                // Desktop must have host networking enabled (it is here).
                .WithCreateParameterModifier(p => p.HostConfig.NetworkMode = "host")
                // The kernel nfsd needs --privileged to mount nfsd/rpc_pipefs and
                // export over the host's NFS module (Docker Desktop's Linux VM
                // provides it). This is the proven path libnfs talks to cleanly.
                .WithPrivileged(true)
                // /data/nfs MUST be a real filesystem (a named volume = ext4) —
                // the kernel nfsd cannot export the container's overlayfs root
                // ("does not support NFS export"), which silently yields empty
                // mounts. The volume is removed on teardown.
                .WithVolumeMount(NfsVolumeName, "/data/nfs")
                // Generated encoder media lands in /media (bind-mounted to the
                // host) so the encoder tests can read it.
                .WithBindMount(MediaDir, "/media")
                .Build();

            await CreateNfsVolumeAsync();
            await _container.StartAsync();

            // Host networking → fixed real ports, no mapping lookup. WebDAV uses
            // 8080 because host port 80 commonly collides with a host service.
            S3Endpoint = "http://localhost:9000";
            WebDavBaseUrl = "http://localhost:8080/";

            await WaitForTcpAsync(9000, TimeSpan.FromSeconds(20));
            await WaitForHttpAsync($"{S3Endpoint}/minio/health/live", TimeSpan.FromSeconds(20));
            await WaitForHttpAsync(
                WebDavBaseUrl,
                TimeSpan.FromSeconds(20),
                expectAnyResponse: true
            );
            await SeedAsync();
            // Samba listens on 1445 (445 is taken by the Windows SMB server).
            await WaitForTcpAsync(SmbPort, TimeSpan.FromSeconds(20));
            // NFS readiness can't be proven by a TCP probe alone — nfsd may
            // accept the connection before the export is serviceable. Retry an
            // actual libnfs mount until it succeeds (or libnfs is absent).
            NfsMountable = await WaitForNfsMountAsync(TimeSpan.FromSeconds(30));

            Available = true;
        }
        catch (Exception ex)
        {
            StartupError = $"{ex.GetType().Name}: {ex.Message}";
            Available = false;
        }
    }

    public async Task DisposeAsync()
    {
        if (_container is not null)
        {
            try
            {
                await _container.DisposeAsync();
            }
            catch
            {
                // Best-effort teardown; Docker GC reclaims a stuck container.
            }
        }

        if (!string.IsNullOrEmpty(_nfsVolumeName))
        {
            try
            {
                await RemoveNfsVolumeAsync();
            }
            catch
            {
                // Best-effort; an orphaned named volume is harmless and GC'd.
            }
        }

        try
        {
            if (!string.IsNullOrEmpty(MediaDir) && Directory.Exists(MediaDir))
                Directory.Delete(MediaDir, recursive: true);
        }
        catch
        {
            // Ignore — temp dir is reclaimed by the OS.
        }
    }

    // ── Backend builders the test classes call ───────────────────────────────

    public AmazonS3Client BuildS3RawClient()
    {
        AmazonS3Config cfg = new()
        {
            ServiceURL = S3Endpoint,
            ForcePathStyle = true,
            AuthenticationRegion = "us-east-1",
        };
        return new(new BasicAWSCredentials(S3AccessKey, S3SecretKey), cfg);
    }

    public S3StorageDriver BuildS3Driver(string? prefix = null) =>
        new(
            bucket: S3Bucket,
            region: "us-east-1",
            prefix: prefix,
            endpoint: S3Endpoint,
            accessKey: S3AccessKey,
            secretKey: S3SecretKey
        );

    public WebDavStorageDriver BuildWebDavDriver()
    {
        WebDavClient client = new(
            new WebDavClientParams
            {
                BaseAddress = new(WebDavBaseUrl),
                Credentials = new NetworkCredential(WebDavUser, WebDavPassword),
            }
        );
        return new(client, WebDavBaseUrl);
    }

    public SmbStorageDriver BuildSmbDriver(string basePath = "")
    {
        SmbDriverConfig config = SmbDriverConfig.For(
            host: SmbHost,
            share: SmbShare,
            username: SmbUser,
            password: SmbPassword,
            port: SmbPort,
            basePath: basePath
        );
        return new(config);
    }

    /// <summary>
    /// Builds an NFS driver against the container's export, or returns null when
    /// the libnfs native library isn't installed (the only reason this can fail
    /// once the container is up).
    /// </summary>
    public NfsStorageDriver? TryBuildNfsDriver(int version = 4)
    {
        try
        {
            NfsDriverConfig config = NfsDriverConfig.For(NfsHost, NfsExport, version: version);
            return new(config);
        }
        catch (DllNotFoundException)
        {
            return null;
        }
    }

    // ── Seeding ──────────────────────────────────────────────────────────────

    private async Task SeedAsync()
    {
        // S3: create the test bucket. (The NFS NAS layout is seeded by the
        // container's entrypoint before nfsd exports it — kernel nfsd serves the
        // already-populated volume, so the seed must land before exportfs.)
        using (AmazonS3Client s3 = BuildS3RawClient())
            await s3.PutBucketAsync(S3Bucket);

        // Encoder media: generate the synthetic fixtures with the container's
        // ffmpeg into /media (host-mapped to MediaDir). Generic names — these
        // are lavfi-generated stand-ins, not real titles.
        await GenerateMediaAsync();
    }

    private async Task GenerateMediaAsync()
    {
        // SD 480p
        await FfmpegAsync(
            "-y -f lavfi -i testsrc2=size=854x480:rate=25:duration=5 "
                + "-f lavfi -i sine=frequency=440:duration=5 "
                + "-c:v libx264 -preset ultrafast -crf 30 -c:a aac -b:a 96k "
                + "/media/video-sd480p.mkv"
        );
        // 1080p
        await FfmpegAsync(
            "-y -f lavfi -i testsrc2=size=1920x1080:rate=25:duration=5 "
                + "-f lavfi -i sine=frequency=440:duration=5 "
                + "-c:v libx264 -preset ultrafast -crf 30 -c:a aac -b:a 96k "
                + "/media/video-1080p.mkv"
        );
        // HDR10 (PQ / BT.2020) — color-tag the stream so MediaAnalyzer classifies it HDR.
        await FfmpegAsync(
            "-y -f lavfi -i testsrc2=size=1920x1080:rate=25:duration=5 "
                + "-vf format=yuv420p10le,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc "
                + "-c:v libx265 -preset ultrafast -x265-params hdr10=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc "
                + "-color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc "
                + "/media/video-hdr10.mkv"
        );
        // Audio-only FLAC
        await FfmpegAsync(
            "-y -f lavfi -i sine=frequency=440:duration=5 -c:a flac " + "/media/audio-only.flac"
        );
    }

    private Task FfmpegAsync(string args) =>
        ExecAsync("bash", "-c", $"ffmpeg {args} >/dev/null 2>&1");

    private async Task ExecAsync(params string[] command)
    {
        ExecResult result = await _container!.ExecAsync(command);
        if (result.ExitCode != 0)
            throw new InvalidOperationException(
                $"container exec failed ({string.Join(' ', command)}): {result.Stderr}"
            );
    }

    private Task CreateNfsVolumeAsync() => DockerCliAsync("volume", "create", NfsVolumeName);

    private Task RemoveNfsVolumeAsync() => DockerCliAsync("volume", "rm", "-f", NfsVolumeName);

    private static async Task DockerCliAsync(params string[] args)
    {
        System.Diagnostics.ProcessStartInfo psi = new("docker")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        foreach (string arg in args)
            psi.ArgumentList.Add(arg);

        using System.Diagnostics.Process proc = System.Diagnostics.Process.Start(psi)!;
        await proc.WaitForExitAsync();
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Waits until the NFS export is mountable and the seeded layout is visible.
    /// The probe is READ-ONLY on purpose: opening a file for write establishes
    /// NFSv4 open-owner seqid state on the shared per-process client id, which
    /// then collides with the first test driver's write (NFS4ERR_BAD_SEQID). A
    /// read-only mount + DirectoryExists proves serviceability without leaving
    /// that state behind. Returns false only when libnfs is absent.
    /// </summary>
    private async Task<bool> WaitForNfsMountAsync(TimeSpan timeout)
    {
        // Give the nfsd grace window (entrypoint sets it to ~10s) time to clear
        // before the first mount, so the first real write isn't rejected.
        await Task.Delay(TimeSpan.FromSeconds(12));

        DateTime deadline = DateTime.UtcNow + timeout;
        while (DateTime.UtcNow < deadline)
        {
            try
            {
                using NfsStorageDriver probe = new(
                    NfsDriverConfig.For(NfsHost, NfsExport, version: 4)
                );
                // Read-only readiness: the seeded /Music must be visible.
                if (probe.DirectoryExists("/Music"))
                    return true;
                await Task.Delay(1000);
            }
            catch (DllNotFoundException)
            {
                NfsUnavailableReason = "libnfs native library not installed";
                return false;
            }
            catch (Exception ex)
            {
                NfsUnavailableReason = ex.Message;
                await Task.Delay(1000);
            }
        }
        return false;
    }

    private static async Task WaitForHttpAsync(
        string url,
        TimeSpan timeout,
        bool expectAnyResponse = false
    )
    {
        DateTime deadline = DateTime.UtcNow + timeout;
        using HttpClient http = new() { Timeout = TimeSpan.FromSeconds(3) };
        while (DateTime.UtcNow < deadline)
        {
            try
            {
                HttpResponseMessage response = await http.GetAsync(url);
                // A reachable WebDAV root answers 401 (auth) — any HTTP status
                // means the server is up; only a transport failure means "wait".
                if (expectAnyResponse || response.IsSuccessStatusCode)
                    return;
            }
            catch
            {
                // not up yet
            }
            await Task.Delay(500);
        }
    }

    private static async Task WaitForTcpAsync(int port, TimeSpan timeout)
    {
        DateTime deadline = DateTime.UtcNow + timeout;
        while (DateTime.UtcNow < deadline)
        {
            try
            {
                using TcpClient client = new();
                await client.ConnectAsync("localhost", port);
                if (client.Connected)
                    return;
            }
            catch
            {
                await Task.Delay(500);
            }
        }
    }

    private static string LocateContainerDir()
    {
        // Walk up from the test bin/ to the source Container/ folder.
        string dir = AppContext.BaseDirectory;
        for (int i = 0; i < 8 && dir.Length > 3; i++)
        {
            string candidate = Path.Combine(dir, "Container", "Dockerfile");
            if (File.Exists(candidate))
                return Path.Combine(dir, "Container");

            string srcCandidate = Path.Combine(
                dir,
                "tests",
                "NoMercy.Tests.Storage",
                "Container",
                "Dockerfile"
            );
            if (File.Exists(srcCandidate))
                return Path.GetDirectoryName(srcCandidate)!;

            dir = Path.GetDirectoryName(dir.TrimEnd(Path.DirectorySeparatorChar)) ?? dir;
        }

        throw new FileNotFoundException(
            "Could not locate the storage-backends Container/Dockerfile relative to "
                + AppContext.BaseDirectory
        );
    }
}

[CollectionDefinition("StorageBackends")]
public sealed class StorageBackendsCollection : ICollectionFixture<StorageBackendsFixture> { }
