namespace NoMercy.Encoder.Format.Rules;

public class Languages
{
    public static readonly string Aar = "aar";
    public static readonly string Abk = "abk";
    public static readonly string Afr = "afr";
    public static readonly string Aka = "aka";
    public static readonly string Alb = "alb";
    public static readonly string Amh = "amh";
    public static readonly string Ara = "ara";
    public static readonly string Arg = "arg";
    public static readonly string Arm = "arm";
    public static readonly string Asm = "asm";
    public static readonly string Ava = "ava";
    public static readonly string Ave = "ave";
    public static readonly string Aym = "aym";
    public static readonly string Aze = "aze";
    public static readonly string Bak = "bak";
    public static readonly string Bam = "bam";
    public static readonly string Baq = "baq";
    public static readonly string Bel = "bel";
    public static readonly string Ben = "ben";
    public static readonly string Bih = "bih";
    public static readonly string Bis = "bis";
    public static readonly string Bos = "bos";
    public static readonly string Bre = "bre";
    public static readonly string Bul = "bul";
    public static readonly string Bur = "bur";
    public static readonly string Cat = "cat";
    public static readonly string Cha = "cha";
    public static readonly string Che = "che";
    public static readonly string Chi = "chi";
    public static readonly string Chu = "chu";
    public static readonly string Chv = "chv";
    public static readonly string Cor = "cor";
    public static readonly string Cos = "cos";
    public static readonly string Cre = "cre";
    public static readonly string Cze = "cze";
    public static readonly string Dan = "dan";
    public static readonly string Div = "div";
    public static readonly string Dut = "dut";
    public static readonly string Dzo = "dzo";
    public static readonly string Eng = "eng";
    public static readonly string Epo = "epo";
    public static readonly string Est = "est";
    public static readonly string Ewe = "ewe";
    public static readonly string Fao = "fao";
    public static readonly string Fij = "fij";
    public static readonly string Fil = "fil";
    public static readonly string Fin = "fin";
    public static readonly string Fre = "fre";
    public static readonly string Fry = "fry";
    public static readonly string Ful = "ful";
    public static readonly string Geo = "geo";
    public static readonly string Ger = "ger";
    public static readonly string Gla = "gla";
    public static readonly string Gle = "gle";
    public static readonly string Glg = "glg";
    public static readonly string Glv = "glv";
    public static readonly string Gre = "gre";
    public static readonly string Grn = "grn";
    public static readonly string Gsw = "gsw";
    public static readonly string Guj = "guj";
    public static readonly string Hat = "hat";
    public static readonly string Hau = "hau";
    public static readonly string Haw = "haw";
    public static readonly string Heb = "heb";
    public static readonly string Her = "her";
    public static readonly string Hin = "hin";
    public static readonly string Hmo = "hmo";
    public static readonly string Hrv = "hrv";
    public static readonly string Hun = "hun";
    public static readonly string Ibo = "ibo";
    public static readonly string Ice = "ice";
    public static readonly string Ido = "ido";
    public static readonly string Iii = "iii";
    public static readonly string Iku = "iku";
    public static readonly string Ile = "ile";
    public static readonly string Ina = "ina";
    public static readonly string Ind = "ind";
    public static readonly string Ipk = "ipk";
    public static readonly string Ita = "ita";
    public static readonly string Jav = "jav";
    public static readonly string Jpn = "jpn";
    public static readonly string Kan = "kan";
    public static readonly string Kas = "kas";
    public static readonly string Kau = "kau";
    public static readonly string Kaz = "kaz";
    public static readonly string Khm = "khm";
    public static readonly string Kik = "kik";
    public static readonly string Kin = "kin";
    public static readonly string Kir = "kir";
    public static readonly string Kom = "kom";
    public static readonly string Kon = "kon";
    public static readonly string Kor = "kor";
    public static readonly string Kua = "kua";
    public static readonly string Kur = "kur";
    public static readonly string Lao = "lao";
    public static readonly string Lat = "lat";
    public static readonly string Lav = "lav";
    public static readonly string Lim = "lim";
    public static readonly string Lin = "lin";
    public static readonly string Lit = "lit";
    public static readonly string Ltz = "ltz";
    public static readonly string Lub = "lub";
    public static readonly string Lug = "lug";
    public static readonly string Mac = "mac";
    public static readonly string Mah = "mah";
    public static readonly string Mal = "mal";
    public static readonly string Mao = "mao";
    public static readonly string Mar = "mar";
    public static readonly string May = "may";
    public static readonly string Mlg = "mlg";
    public static readonly string Mlt = "mlt";
    public static readonly string Mon = "mon";
    public static readonly string Nau = "nau";
    public static readonly string Nav = "nav";
    public static readonly string Nbl = "nbl";
    public static readonly string Nde = "nde";
    public static readonly string Ndo = "ndo";
    public static readonly string Nep = "nep";
    public static readonly string Nno = "nno";
    public static readonly string Nob = "nob";
    public static readonly string Nor = "nor";
    public static readonly string Nya = "nya";
    public static readonly string Oci = "oci";
    public static readonly string Oji = "oji";
    public static readonly string Ori = "ori";
    public static readonly string Orm = "orm";
    public static readonly string Oss = "oss";
    public static readonly string Pan = "pan";
    public static readonly string Per = "per";
    public static readonly string Pli = "pli";
    public static readonly string Pol = "pol";
    public static readonly string Por = "por";
    public static readonly string Pus = "pus";
    public static readonly string Que = "que";
    public static readonly string Roh = "roh";
    public static readonly string Rum = "rum";
    public static readonly string Run = "run";
    public static readonly string Rus = "rus";
    public static readonly string Sag = "sag";
    public static readonly string San = "san";
    public static readonly string Sin = "sin";
    public static readonly string Slo = "slo";
    public static readonly string Slv = "slv";
    public static readonly string Sme = "sme";
    public static readonly string Smo = "smo";
    public static readonly string Sna = "sna";
    public static readonly string Snd = "snd";
    public static readonly string Som = "som";
    public static readonly string Sot = "sot";
    public static readonly string Spa = "spa";
    public static readonly string Srd = "srd";
    public static readonly string Srp = "srp";
    public static readonly string Ssw = "ssw";
    public static readonly string Sun = "sun";
    public static readonly string Swa = "swa";
    public static readonly string Swe = "swe";
    public static readonly string Tah = "tah";
    public static readonly string Tam = "tam";
    public static readonly string Tat = "tat";
    public static readonly string Tel = "tel";
    public static readonly string Tgk = "tgk";
    public static readonly string Tgl = "tgl";
    public static readonly string Tha = "tha";
    public static readonly string Tib = "tib";
    public static readonly string Tir = "tir";
    public static readonly string Ton = "ton";
    public static readonly string Tsn = "tsn";
    public static readonly string Tso = "tso";
    public static readonly string Tuk = "tuk";
    public static readonly string Tur = "tur";
    public static readonly string Twi = "twi";
    public static readonly string Uig = "uig";
    public static readonly string Ukr = "ukr";
    public static readonly string Urd = "urd";
    public static readonly string Uzb = "uzb";
    public static readonly string Ven = "ven";
    public static readonly string Vie = "vie";
    public static readonly string Vol = "vol";
    public static readonly string Wel = "wel";
    public static readonly string Wln = "wln";
    public static readonly string Wol = "wol";
    public static readonly string Xho = "xho";
    public static readonly string Yid = "yid";
    public static readonly string Yor = "yor";
    public static readonly string Zha = "zha";
    public static readonly string Zul = "zul";
    
    public static string[] AllLanguages()
    {
        return
        [
            Aar, Abk, Afr, Aka, Alb, Amh, Ara,
            Arg, Arm, Asm, Ava, Ave, Aym, Aze,
            Bak, Bam, Baq, Bel, Ben, Bih, Bis,
            Bos, Bre, Bul, Bur, Cat, Cha, Che,
            Chi, Chu, Chv, Cor, Cos, Cre, Cze,
            Dan, Div, Dut, Dzo, Eng, Epo, Est,
            Ewe, Fao, Fij, Fil, Fin, Fre, Fry,
            Ful, Geo, Ger, Gla, Gle, Glg, Glv,
            Gre, Grn, Gsw, Guj, Hat, Hau, Haw,
            Heb, Her, Hin, Hmo, Hrv, Hun, Ibo,
            Ice, Ido, Iii, Iku, Ile, Ina, Ind,
            Ita, Jav, Jpn, Kan, Kas, Kau, Kaz,
            Khm, Kik, Kin, Kir, Kom, Kon, Kor,
            Kua, Kur, Lao, Lat, Lav, Lim, Lin,
            Lit, Ltz, Lub, Lug, Mac, Mah, Mal,
            Mao, Mar, May, Mlg, Mlt, Mon, Nau,
            Nav, Nbl, Nde, Ndo, Nep, Nno, Nob,
            Nor, Nya, Oci, Oji, Ori, Orm, Oss,
            Pan, Per, Pli, Pol, Por, Pus, Que,
            Roh, Rum, Run, Rus, Sag, San, Sin,
            Slo, Slv, Sme, Smo, Sna, Snd, Som,
            Sot, Spa, Srd, Srp, Ssw, Sun, Swa,
            Swe, Tah, Tam, Tat, Tel, Tgk, Tgl,
            Tha, Tib, Tir, Ton, Tsn, Tso, Tuk,
            Tur, Twi, Uig, Ukr, Urd, Uzb, Ven,
            Vie, Vol, Wel, Wln, Wol, Xho, Yid,
            Yor, Zha, Zul, Ipk
        ];
    }
}