// -----------------------------------------------------------------------------
//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.
//
//  This file is part of NoMercy MediaServer, source-available software (NOT open
//  source). Personal use and contributions are welcome; distribution, resale,
//  relicensing, and commercial exploitation are prohibited without explicit
//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.
//
//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary
// -----------------------------------------------------------------------------

// Generated by tools/nm-components. Do not edit.

using NoMercy.Design;
using NoMercy.Plugins.Abstractions;

namespace NoMercy.Tests.Api.NmComponents;

/// <summary>
/// Every C# snippet the component documentation publishes, verbatim.
/// <para>
/// It exists to be compiled. The pages tell a plugin author to write this
/// exact code, and a rename in the design system would otherwise leave every
/// one of them wrong with nothing failing anywhere.
/// </para>
/// </summary>
internal static class DocumentedSnippets
{
    private static void avatar()
    {
        NMAvatarProps props = new()
        {
            Id = "avatar-1",
            Size = "xl",
            Status = "busy",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("avatar-1", props);

        _ = node;
    }

    private static void badge()
    {
        NMBadgeProps props = new()
        {
            Id = "badge-1",
            Mode = "icon-only",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("badge-1", props);

        _ = node;
    }

    private static void divider()
    {
        NMDividerProps props = new()
        {
            Id = "divider-1",
            Line = "dotted",
            Placement = "right",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("divider-1", props);

        _ = node;
    }

    private static void formlabel()
    {
        NMFormLabelProps props = new()
        {
            Id = "form-label-1",
            Marker = "custom",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("form-label-1", props);

        _ = node;
    }

    private static void helper()
    {
        NMHelperProps props = new()
        {
            Id = "helper-1",
            Status = "disabled",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("helper-1", props);

        _ = node;
    }

    private static void image()
    {
        NMImageProps props = new()
        {
            Id = "image-1",
            AspectRatio = "landscape",
            Fit = "none",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("image-1", props);

        _ = node;
    }

    private static void link()
    {
        NMLinkProps props = new()
        {
            Id = "link-1",
            IconPosition = "right",
            Size = "inherit",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("link-1", props);

        _ = node;
    }

    private static void progress()
    {
        NMProgressProps props = new()
        {
            Id = "progress-1",
            LabelPos = "tooltip-below",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("progress-1", props);

        _ = node;
    }

    private static void skeleton()
    {
        NMSkeletonProps props = new()
        {
            Id = "skeleton-1",
            Variant = "rectangle",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("skeleton-1", props);

        _ = node;
    }

    private static void spinner()
    {
        NMSpinnerProps props = new()
        {
            Id = "spinner-1",
            Size = "xl",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("spinner-1", props);

        _ = node;
    }

    private static void tag()
    {
        NMTagProps props = new()
        {
            Id = "tag-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("tag-1", props);

        _ = node;
    }

    private static void button()
    {
        NMButtonProps props = new()
        {
            Id = "button-1",
            Layout = "full",
            Size = "2xl",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("button-1", props);

        _ = node;
    }

    private static void checkbox()
    {
        NMCheckboxProps props = new()
        {
            Id = "checkbox-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("checkbox-1", props);

        _ = node;
    }

    private static void input()
    {
        NMInputProps props = new()
        {
            Id = "input-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("input-1", props);

        _ = node;
    }

    private static void radio()
    {
        NMRadioProps props = new()
        {
            Id = "radio-1",
            Size = "md",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("radio-1", props);

        _ = node;
    }

    private static void rating()
    {
        NMRatingProps props = new()
        {
            Id = "rating-1",
            Mode = "interactive",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("rating-1", props);

        _ = node;
    }

    private static void slider()
    {
        NMSliderProps props = new()
        {
            Id = "slider-1",
            LabelMode = "tooltip",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("slider-1", props);

        _ = node;
    }

    private static void textarea()
    {
        NMTextareaProps props = new()
        {
            Id = "textarea-1",
            Resize = "both",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("textarea-1", props);

        _ = node;
    }

    private static void toggle()
    {
        NMToggleProps props = new()
        {
            Id = "toggle-1",
            Size = "md",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("toggle-1", props);

        _ = node;
    }

    private static void badgegroup()
    {
        NMBadgeGroupProps props = new()
        {
            Id = "badge-group-1",
            BadgePos = "right",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("badge-group-1", props);

        _ = node;
    }

    private static void breadcrumb()
    {
        NMBreadcrumbProps props = new()
        {
            Id = "breadcrumb-1",
            Separator = "dot",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("breadcrumb-1", props);

        _ = node;
    }

    private static void buttongroup()
    {
        NMButtonGroupProps props = new()
        {
            Id = "button-group-1",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("button-group-1", props);

        _ = node;
    }

    private static void checkboxgroup()
    {
        NMCheckboxGroupProps props = new()
        {
            Id = "checkbox-group-1",
            Layout = "inline",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("checkbox-group-1", props);

        _ = node;
    }

    private static void pagination()
    {
        NMPaginationProps props = new()
        {
            Id = "pagination-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("pagination-1", props);

        _ = node;
    }

    private static void radiogroup()
    {
        NMRadioGroupProps props = new()
        {
            Id = "radio-group-1",
            Layout = "inline",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("radio-group-1", props);

        _ = node;
    }

    private static void segmented()
    {
        NMSegmentedProps props = new()
        {
            Id = "segmented-1",
            Size = "md",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("segmented-1", props);

        _ = node;
    }

    private static void stepindicator()
    {
        NMStepIndicatorProps props = new()
        {
            Id = "step-indicator-1",
            Size = "lg",
            Variant = "numbers",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("step-indicator-1", props);

        _ = node;
    }

    private static void toggles()
    {
        NMTogglesProps props = new()
        {
            Id = "toggles-1",
            Size = "lg",
            State = "indeterminate",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("toggles-1", props);

        _ = node;
    }

    private static void alert()
    {
        NMAlertProps props = new()
        {
            Id = "alert-1",
            Severity = "error",
            Size = "compact",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("alert-1", props);

        _ = node;
    }

    private static void card()
    {
        NMCardProps props = new()
        {
            Id = "card-1",
            FooterVariant = "helper",
            Padding = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("card-1", props);

        _ = node;
    }

    private static void chat()
    {
        NMChatProps props = new()
        {
            Id = "chat-1",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("chat-1", props);

        _ = node;
    }

    private static void contentfooter()
    {
        NMContentFooterProps props = new()
        {
            Id = "content-footer-1",
            Variant = "helper",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("content-footer-1", props);

        _ = node;
    }

    private static void contentheader()
    {
        NMContentHeaderProps props = new()
        {
            Id = "content-header-1",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("content-header-1", props);

        _ = node;
    }

    private static void emptystate()
    {
        NMEmptyStateProps props = new()
        {
            Id = "empty-state-1",
            Variant = "card",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("empty-state-1", props);

        _ = node;
    }

    private static void list()
    {
        NMListProps props = new()
        {
            Id = "list-1",
            Bullet = "dash",
            Order = "upper-roman",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("list-1", props);

        _ = node;
    }

    private static void metrics()
    {
        NMMetricsProps props = new()
        {
            Id = "metrics-1",
            Trend = "neutral",
            Variant = "compact",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("metrics-1", props);

        _ = node;
    }

    private static void table()
    {
        NMTableProps props = new()
        {
            Id = "table-1",
            Size = "lg",
            Variant = "minimal",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("table-1", props);

        _ = node;
    }

    private static void colorpicker()
    {
        NMColorPickerProps props = new()
        {
            Id = "color-picker-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("color-picker-1", props);

        _ = node;
    }

    private static void combobox()
    {
        NMComboboxProps props = new()
        {
            Id = "combobox-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("combobox-1", props);

        _ = node;
    }

    private static void commandpalette()
    {
        NMCommandPaletteProps props = new()
        {
            Id = "command-palette-1",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("command-palette-1", props);

        _ = node;
    }

    private static void datepicker()
    {
        NMDatePickerProps props = new()
        {
            Id = "date-picker-1",
            Mode = "dual",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("date-picker-1", props);

        _ = node;
    }

    private static void drawer()
    {
        NMDrawerProps props = new()
        {
            Id = "drawer-1",
            Position = "bottom",
            Size = "full",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("drawer-1", props);

        _ = node;
    }

    private static void dropdown()
    {
        NMDropdownProps props = new()
        {
            Id = "dropdown-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("dropdown-1", props);

        _ = node;
    }

    private static void modal()
    {
        NMModalProps props = new()
        {
            Id = "modal-1",
            FooterVariant = "helper",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("modal-1", props);

        _ = node;
    }

    private static void popover()
    {
        NMPopoverProps props = new()
        {
            Id = "popover-1",
            Position = "left",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("popover-1", props);

        _ = node;
    }

    private static void searchinput()
    {
        NMSearchInputProps props = new()
        {
            Id = "search-input-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("search-input-1", props);

        _ = node;
    }

    private static void select()
    {
        NMSelectProps props = new()
        {
            Id = "select-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("select-1", props);

        _ = node;
    }

    private static void toast()
    {
        NMToastProps props = new()
        {
            Id = "toast-1",
            Position = "bottom-right",
            Variant = "error",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("toast-1", props);

        _ = node;
    }

    private static void tooltip()
    {
        NMTooltipProps props = new()
        {
            Id = "tooltip-1",
            Position = "left",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("tooltip-1", props);

        _ = node;
    }

    private static void accordion()
    {
        NMAccordionProps props = new()
        {
            Id = "accordion-1",
            Size = "lg",
            Variant = "ghost",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("accordion-1", props);

        _ = node;
    }

    private static void carousel()
    {
        NMCarouselProps props = new()
        {
            Id = "carousel-1",
            Size = "full",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("carousel-1", props);

        _ = node;
    }

    private static void fileupload()
    {
        NMFileUploadProps props = new()
        {
            Id = "file-upload-1",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("file-upload-1", props);

        _ = node;
    }

    private static void navigation()
    {
        NMNavigationProps props = new()
        {
            Id = "navigation-1",
            Variant = "pills",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("navigation-1", props);

        _ = node;
    }

    private static void stepper()
    {
        NMStepperProps props = new()
        {
            Id = "stepper-1",
            Orientation = "vertical",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("stepper-1", props);

        _ = node;
    }

    private static void tabs()
    {
        NMTabsProps props = new()
        {
            Id = "tabs-1",
            Size = "lg",
            Variant = "enclosed",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("tabs-1", props);

        _ = node;
    }

    private static void treeview()
    {
        NMTreeViewProps props = new()
        {
            Id = "tree-view-1",
            Size = "lg",
            Box = new() { Margin = new() { Y = NmSpace.X4 }, Padding = new() { All = NmSpace.X3 } },
        };
        
        // In a plugin, the record becomes a node the client draws:
        PluginComponent node = PluginDesign.Node("tree-view-1", props);

        _ = node;
    }
}
