<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
    <PackageReference Include="Vortice.DXGI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoMercy.Database\NoMercy.Database.csproj" />
    <ProjectReference Include="..\NoMercy.NmSystem\NoMercy.NmSystem.csproj" />
  </ItemGroup>

</Project>
