#!/bin/sh
set -e

# Reload systemd user daemon
systemctl --user daemon-reload || true

# Enable and start service
if [ -n "$SUDO_USER" ]; then
su - $SUDO_USER -c "systemctl --user enable nomercyupdater.service" || true
su - $SUDO_USER -c "systemctl --user start nomercyupdater.service" || true
fi

exit 0
