#!/bin/sh
set -e
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user stop nomercymediaserver.service >/dev/null 2>&1 || true
    systemctl --user disable nomercymediaserver.service >/dev/null 2>&1 || true
    systemctl --user stop nomercylauncher.service >/dev/null 2>&1 || true
    systemctl --user disable nomercylauncher.service >/dev/null 2>&1 || true
fi
exit 0
