global using NoMercy.Database.Models.Common;
global using NoMercy.Database.Models.Libraries;
global using NoMercy.Database.Models.Media;
global using NoMercy.Database.Models.Movies;
global using NoMercy.Database.Models.Music;
global using NoMercy.Database.Models.People;
global using NoMercy.Database.Models.Queue;
global using NoMercy.Database.Models.TvShows;
global using NoMercy.Database.Models.Users;
