<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NoMercy.OpticalMedia</RootNamespace>
    <AssemblyName>NoMercy.OpticalMedia</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoMercy.Events\NoMercy.Events.csproj" />
    <ProjectReference Include="..\NoMercy.Globals\NoMercy.Globals.csproj" />
    <ProjectReference Include="..\NoMercy.Helpers\NoMercy.Helpers.csproj" />
    <ProjectReference Include="..\NoMercy.NmSystem\NoMercy.NmSystem.csproj" />
    <ProjectReference Include="..\NoMercy.Providers\NoMercy.Providers.csproj" />
    <ProjectReference Include="..\NoMercy.Storage\NoMercy.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Management" Condition="$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))" />
  </ItemGroup>
</Project>
