name: 'Setup .NET Environment'
description: 'Common setup steps for .NET projects including checkout, .NET setup, caching, and restore'

inputs:
  dotnet-version:
    description: '.NET version to use'
    required: false
    default: '9.0.x'
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags'
    required: false
    default: '1'
  fetch-tags:
    description: 'Whether to fetch tags'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      shell: bash
      run: dotnet restore NoMercy.Server.sln --verbosity minimal
