name: Build Executables

on:
  workflow_run:
    workflows: ["Test and Create Pull Request to Master"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  build_executables:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .NET SDK for the NoMercy.Server project
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # Restore dependencies for the NoMercy.Server project
      - name: Restore dependencies
        run: dotnet restore NoMercy.Server.sln

      # Build the NoMercy.Server project
      - name: Build NoMercy.Server
        run: |
          dotnet build ./src/NoMercy.Server/NoMercy.Server.csproj --configuration Release --runtime linux-x64
          dotnet build ./src/NoMercy.Server/NoMercy.Server.csproj --configuration Release --runtime win-x64
          dotnet build ./src/NoMercy.Server/NoMercy.Server.csproj --configuration Release --runtime osx-x64

      # Publish the NoMercy.Server project for the target OS
      - name: Publish NoMercy.Server
        run: |
          mkdir -p ./output
      
          # Publish for Linux
          dotnet publish ./src/NoMercy.Server/NoMercy.Server.csproj --configuration Release --runtime linux-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:IncludeAllContentForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:DebugType=None /p:DebugSymbols=false /p:PublishReadyToRun=true /p:PublishTrimmed=true --output ./output
          mv ./output/NoMercyMediaServer ./output/NoMercyMediaServer-linux-x64
      
          # Publish for Windows
          dotnet publish ./src/NoMercy.Server/NoMercy.Server.csproj --configuration Release --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:IncludeAllContentForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:DebugType=None /p:DebugSymbols=false /p:PublishReadyToRun=true /p:PublishTrimmed=true --output ./output
      
          # Publish for macOS
          dotnet publish ./src/NoMercy.Server/NoMercy.Server.csproj --configuration Release --runtime osx-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:IncludeAllContentForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:DebugType=None /p:DebugSymbols=false /p:PublishReadyToRun=true /p:PublishTrimmed=true --output ./output
          mv ./output/NoMercyMediaServer ./output/NoMercyMediaServer-macos-x64
          
      # Create the GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: NoMercy MediaServer Release
          body: |
            New release for NoMercy MediaServer is ready.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Windows Release Asset
      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/NoMercyMediaServer.exe
          asset_name: NoMercyMediaServer.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      # Upload macOS Release Asset
      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/NoMercyMediaServer-macos-x64
          asset_name: NoMercyMediaServer-macos-x64
          asset_content_type: application/x-apple-diskimage

      # Upload Linux Release Asset
      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/NoMercyMediaServer-linux-x64
          asset_name: NoMercyMediaServer-linux-x64
          asset_content_type: application/x-executable
