name: CI

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ "windows-latest" ]

    runs-on: "${{ matrix.os }}"  
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore dependencies
        run: dotnet restore NoMercy.Server.sln

      - name: Test
        run: dotnet test NoMercy.Server.sln --verbosity normal --collect:"XPlat Code Coverage"
