name: CI

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: "${{ matrix.os }}"  
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Install Android Maui
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: dotnet workload install maui-android

      - name: Restore dependencies
        run: dotnet restore NoMercy.Server.sln

      - name: Test
        run: >
          dotnet test NoMercy.Server.sln 
          --configuration Release
          --collect:"XPlat Code Coverage"
          --settings tests/coverletArgs.runsettings
          --verbosity minimal
