name: Test and Create Pull Request to Master

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  test_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .NET SDK for the NoMercy.Server project
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # Restore dependencies for the NoMercy.Server project
      - name: Restore dependencies
        run: dotnet restore NoMercy.Server.sln

      # Run tests
      - name: Test
        run: >
          dotnet test NoMercy.Server.sln 
          --configuration Release
          --collect:"XPlat Code Coverage"
          --settings tests/coverletArgs.runsettings
          --verbosity minimal

      # Directly merge from dev to master
      - name: Merge Dev into Master
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Checkout master branch and ensure it's up-to-date
          git checkout master
          git fetch origin master:master
          git fetch origin dev:dev

          # Merge dev into master
          git merge dev --no-ff --no-commit --allow-unrelated-histories
          
          # Push the changes to master
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}