name: Test and Create Pull Request to Master

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  test_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .NET SDK for the NoMercy.Server project
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # Restore dependencies for the NoMercy.Server project
      - name: Restore dependencies
        run: dotnet restore NoMercy.Server.sln

      # Run tests
      - name: Test
        run: >
          dotnet test NoMercy.Server.sln 
          --configuration Release
          --collect:"XPlat Code Coverage"
          --settings tests/coverletArgs.runsettings
          --verbosity minimal

      # Create a Pull Request to master (or main)
      - name: Create Pull Request from Dev to Master
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout dev
          git fetch origin master
          git checkout -b pr-to-master
          git merge origin/master --no-ff --no-commit --allow-unrelated-histories
          git push --set-upstream origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Merge the Pull Request after creation
      - name: Merge Pull Request
        if: success()
        run: |
          PR_ID=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d '{"title":"Merge Dev into Master","head":"dev","base":"master"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls | jq -r '.number')
          curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X PUT \
            -d '{"commit_title":"Merging Dev into Master","merge_method":"merge"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID/merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
