name: Create and Upload Release

on:
  workflow_run:
    workflows: ["Build Executables"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  create_and_upload_release:
    runs-on: ubuntu-latest

    steps:
      # Download the uploaded executables artifact
      - name: Download Executables Artifact
        uses: actions/download-artifact@v2
        with:
          name: executables

      # Create the GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: NoMercy MediaServer Release
          body: |
            New release for NoMercy MediaServer is ready.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Windows Release Asset
      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/NoMercyMediaServer.exe
          asset_name: NoMercyMediaServer.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      # Upload macOS Release Asset
      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/NoMercyMediaServer.dmg
          asset_name: NoMercyMediaServer.dmg
          asset_content_type: application/x-apple-diskimage

      # Upload Linux Release Asset
      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/NoMercyMediaServer
          asset_name: NoMercyMediaServer
          asset_content_type: application/x-executable
